### ISSUE TITLE
svg-sprite-loader 配置了不生效

### ISSUE THREAD

**Issue by codcer** [efoxTeam/emp#103]
![image](https://user-images.githubusercontent.com/7337505/111859936-49fb7400-897f-11eb-8b6e-568a5b0291ba.png)

**Comment by leizp** [comment]
问下怎么解决的呀？ 我配置了也不生效

**Comment by codcer** [comment]
// 让其他svg loader不对src/assets/icon进行操作
  config.module.rule('svg').exclude.add(resolveApp('src/assets/svgs')).end();
  config.module
    .rule('icon')
    .test(/\.svg$/)
    .include.add(resolveApp('src/assets/svgs'))
    .end()
    .use('svg-sprite-loader')
    .loader('svg-sprite-loader')
    .options({
      symbolId: 'icon-[name]',
    })
    .end();

**Comment by codcer** [comment]
> 问下怎么解决的呀？ 我配置了也不生效
// 让其他svg loader不对src/assets/icon进行操作
config.module.rule('svg').exclude.add(resolveApp('src/assets/svgs')).end();
config.module
.rule('icon')
.test(/.svg$/)
.include.add(resolveApp('src/assets/svgs'))
.end()
.use('svg-sprite-loader')
.loader('svg-sprite-loader')
.options({
symbolId: 'icon-[name]',
})
.end();
