### ISSUE TITLE
重新安装了一下node-modules 后启动不起来

### ISSUE THREAD

**Issue by leizp** [efoxTeam/emp#107]
(node:18876) UnhandledPromiseRejectionWarning: ValidationError: Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.      
 - configuration has an unknown property 'overlay'. These properties are valid:
   object { bonjour?, client?, compress?, dev?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, https?, injectClient?, injectHot?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, openPage?, port?, proxy?, public?, setupExitSignals?, static?, stdin?, transportMode?, useLocalIp? }
    at validate (D:\work\lzu_work\work\git-work\lzu-micro\main-react\node_modules\schema-utils\dist\validate.js:104:11)
    at new Server (D:\work\lzu_work\work\git-work\lzu-micro\main-react\node_modules\webpack-dev-server\lib\Server.js:43:5)
    at module.exports (D:\work\lzu_work\work\git-work\lzu-micro\main-react\node_modules\@efox\emp-cli\scripts\dev.js:19:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ckken** [comment]
overlay 应该是没问题的 可否看看你 webpack-dev-server 版本

**Comment by ckken** [comment]
fixed it https://github.com/efoxTeam/emp/commit/e40f50069dbcdfe0989167e6e800aa8c16084f6a
