### ISSUE TITLE
react 封装svg组建后不显示，

### ISSUE THREAD

**Issue by leizp** [efoxTeam/emp#108]
"svg-sprite-loader": "^6.0.2",

# webpack配置如下

// 设置svg loader
  config.module.rule('svg').exclude.add(resolve('src/icons')).end()
  config.module
    .rule('icons')
    .test(/\.svg$/)
    .include.add(resolve('src/icons'))
    .end()
    .use('svg-sprite-loader')
    .loader('svg-sprite-loader')
    .options({
      symbolId: 'icon-[name]',
    })
    .end()

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/tree/main/projects/empty-project 这里有demo

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/blob/e40f50069dbcdfe0989167e6e800aa8c16084f6a/projects/empty-project/src/App.tsx#L37
