### ISSUE TITLE
开发时有时候控制台会崩溃

### ISSUE THREAD

**Issue by DIVINER-onlys** [efoxTeam/emp#11]
<--- Last few GCs --->

[51786:0x10461d000] 14908944 ms: Scavenge (reduce) 2042.8 (2052.3) -> 2042.1 (2052.3) MB, 27.5 / 0.0 ms  (average mu = 0.108, current mu = 0.095) allocation failure 
[51786:0x10461d000] 14908985 ms: Scavenge (reduce) 2043.0 (2052.3) -> 2042.4 (2052.3) MB, 23.4 / 0.0 ms  (average mu = 0.108, current mu = 0.095) allocation failure 
[51786:0x10461d000] 14909033 ms: Scavenge (reduce) 2043.2 (2052.3) -> 2042.5 (2052.5) MB, 22.0 / 0.0 ms  (average mu = 0.108, current mu = 0.095) allocation failure 

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1012762c5 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000a2899 node::Abort() [/usr/local/bin/node]
 3: 0x1000a29ff node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001e45b7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1001e4553 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x10037dda5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x10037f61a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 8: 0x10037b5b7 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x100378f88 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
10: 0x1003863da v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x100386461 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
12: 0x100355c17 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
13: 0x1006cd948 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x100a24519 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
15: 0x100a2db51 Builtins_SetPropertyInLiteral [/usr/local/bin/node]
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by flyyuan** [comment]
升级 node 到最新版
