### ISSUE TITLE
babel报错，这个是什么原因呀

### ISSUE THREAD

**Issue by longkehuawei** [efoxTeam/emp#112]
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* D:\rule\urule-console-js\node_modules\babel-loader\lib\index.js??ruleSet[1].rules[11].use[0]!D:\rule\urule-console-js\src\policyTreeList\req.js
    Used by 1 module(s), i. e.
    D:\rule\urule-console-js\node_modules\babel-loader\lib\index.js??ruleSet[1].rules[11].use[0]!D:\rule\urule-console-js\src\policyTreeList\action.js
* D:\rule\urule-console-js\node_modules\babel-loader\lib\index.js??ruleSet[1].rules[11].use[0]!D:\rule\urule-console-js\src\policytreelist\req.js
    Used by 2 module(s), i. e.
    D:\rule\urule-console-js\node_modules\babel-loader\lib\index.js??ruleSet[1].rules[11].use[0]!D:\rule\urule-console-js\src\policytreelist\index.jsx
 @ ./src/policyTreeList/action.js 1:0-29 30:4-20 46:4-24 66:4-24 88:4-28
 @ ./src/policyTreeList/reducer.js 8:0-39 65:10-33 89:18-36 95:10-27 113:9-37 135:9-30 147:9-30 152:9-23 162:9-27 182:9-29 190:9-38
 @ ./src/router/reducer.js 6:0-55 22:18-32
 @ ./src/router/index.jsx 9:0-40 11:24-35
 @ container entry ./components/Hello[0]

**Comment by longkehuawei** [comment]
react 工程

**Comment by ckken** [comment]
先把代码仓库和 codepen 贴出来

**Comment by longkehuawei** [comment]
用demo就行了，公司不准上传东西，脚手架搭建的vue工程好像就报这个错误
{
  "name": "hello",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "dev": "emp dev",
    "build": "emp build --env prod",
    "start": "emp serve",
    "stat": "emp build --analyze",
    "emp": "emp",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "^2.6.11",
    "@efox/emp-cli": "latest",
    "@efox/emp-vue2": "latest"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
