### ISSUE TITLE
react-redux 根组件怎么暴露呀

### ISSUE THREAD

**Issue by longkehuawei** [efoxTeam/emp#117]
ReactDOM.render(
    <Provider store={store}>
        <Router>
            <MyLayout>
                <Switch>
                    {
                        secroutes.map(pItem => {
                            return (
                                pItem.children.map(item => {
                                    return (<Route key={item.path} path={item.path} component={item.component}/>);
                                })
                            );
                        })
                    }
                    <Redirect from="/" to="/urule/router" exact></Redirect>
                    <Redirect to="/urule/router" exact></Redirect>
                </Switch>
            </MyLayout>
        </Router>
    </Provider>
    , document.getElementById('app'));

**Comment by ckken** [comment]
可以参考 mobx https://github.com/efoxTeam/emp/blob/main/projects/antd-base/src/App.tsx
