### ISSUE TITLE
这个是什么错误呀，升级node之后报错了

### ISSUE THREAD

**Issue by longkehuawei** [efoxTeam/emp#118]
yarn run v1.22.10
$ emp dev
╔════════════════════╤═══════════════╗
║ Emp & Deps         │ Version       ║
╟────────────────────┼───────────────╢
║ @efox/emp-cli      │ 1.8.13        ║
╟────────────────────┼───────────────╢
║ webpack            │ ^5.30.0       ║
╟────────────────────┼───────────────╢
║ webpack-dev-server │ ^4.0.0-beta.1 ║
╟────────────────────┼───────────────╢
║ typescript         │ ^4.1.3        ║
╟────────────────────┼───────────────╢
║ postcss            │ ^8.2.8        ║
╚════════════════════╧═══════════════╝

internal/fs/utils.js:307
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\l01036\AppData\Local\Yarn\Data\global/node_modules'
    at Object.readdirSync (fs.js:1021:3)
    at globalPlugin (D:\rule\urule-console-js\node_modules\@efox\emp-cli\helpers\pluginDriver.js:14:34)
    at pluginDriver (D:\rule\urule-console-js\node_modules\@efox\emp-cli\helpers\pluginDriver.js:48:30)
    at Object.<anonymous> (D:\rule\urule-console-js\node_modules\@efox\emp-cli\bin\emp.js:306:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\l01036\\AppData\\Local\\Yarn\\Data\\global/node_modules'
}
error Command failed with exit code 1.

**Comment by flyyuan** [comment]
升级 emp-cli 到 1.8.14

**Comment by longkehuawei** [comment]
是不是有缓存呀，我把node 降到之前版本，拉取到的还是1.8.14

**Comment by flyyuan** [comment]
升级到 1.8.14 还会报错？如果会，贴一下错误

**Comment by longkehuawei** [comment]
现在不报错了，问一下，在Vue主工程 中怎么设置proxy，在emp-config.js中配置的么

**Comment by flyyuan** [comment]
在Vue主工程中怎么设置 proxy 的问题新提一个 issue 哈

**Comment by longkehuawei** [comment]
集成Vue主工程还是报错呀， emp dev
╔════════════════════╤═══════════════╗
║ Emp & Deps         │ Version       ║
╟────────────────────┼───────────────╢
║ @efox/emp-cli      │ 1.6.17        ║
╟────────────────────┼───────────────╢
║ webpack            │ ^5.14.0       ║
╟────────────────────┼───────────────╢
║ webpack-dev-server │ ^4.0.0-beta.0 ║
╟────────────────────┼───────────────╢
║ typescript         │ ^4.1.3        ║
╟────────────────────┼───────────────╢
║ postcss            │ ^8.2.1        ║
╚════════════════════╧═══════════════╝

config { host: 'localhost',
  port: 6007,
  publicPath: 'http://localhost:6007/' }

* Webpack █████████████████████████  (0%)


(node:3404) UnhandledPromiseRejectionWarning: ValidationError: Invalid configuration object. Object has been initia
lized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'overlay'. These properties are valid:
   object { bonjour?, client?, compress?, dev?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, http
s?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, public?, se
tupExitSignals?, static?, transportMode?, watchFiles? }
    at validate (D:\toB\ui\node_modules\schema-utils\dist\validate.js:104:11)
    at new Server (D:\toB\ui\node_modules\webpack-dev-server\lib\Server.js:43:5)
    at module.exports (D:\toB\ui\node_modules\@efox\emp-cli\scripts\dev.js:15:18)
(node:3404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing
 inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
(rejection id: 1)
(node:3404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejec
tions that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 7.71s.

**Comment by flyyuan** [comment]
发一下 rope ，帮你看看

**Comment by longkehuawei** [comment]
package.json
{
  "name": "management-demo",
  "version": "3.4.0",
  "description": "ToB后台管理系统",
  "author": "smy",
  "main": "index.js",
  "license": "MIT",
  "scripts": {

    "dev": "vue-cli-service serve",
    "build:prod": "vue-cli-service build",
    "build:stage": "vue-cli-service build --mode staging",
    "preview": "node build/index.js --preview",
    "dev": "emp dev",
    "build": "emp build --env prod",
    "start": "emp serve",
    "stat": "emp build --analyze",
    "emp": "emp",
    "lint": "eslint --ext .js,.vue src"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "src/**/*.{js,vue}": [
      "eslint --fix",
      "git add"
    ]
  },
  "keywords": [
    "vue",
    "admin",
    "dashboard",
    "element-ui",
    "boilerplate",
    "admin-template",
    "management-system"
  ],
  "repository": {
    "type": "git",
    "url": "https://gitee.com/y_project/RuoYi-Vue.git"
  },
  "dependencies": {
    "@riophae/vue-treeselect": "0.4.0",
    "axios": "0.21.0",
    "clipboard": "2.0.6",
    "core-js": "3.8.1",
    "echarts": "4.9.0",
    "element-ui": "2.15.0",
    "file-saver": "2.0.4",
    "fuse.js": "6.4.3",
    "highlight.js": "9.18.5",
    "js-beautify": "1.13.0",
    "js-cookie": "2.2.1",
    "jsencrypt": "3.0.0-rc.1",
    "nprogress": "0.2.0",
    "quill": "1.3.7",
    "screenfull": "5.0.2",
    "sortablejs": "1.10.2",
    "vue": "2.6.12",
    "vue-count-to": "1.0.13",
    "vue-cropper": "0.5.5",
    "vue-router": "3.4.9",
    "vuedraggable": "2.24.3",
    "vuex": "3.6.0",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "vuera": "^0.2.7"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "4.4.6",
    "@vue/cli-plugin-eslint": "4.4.6",
    "@vue/cli-service": "4.5.12",
    "babel-eslint": "10.1.0",
    "chalk": "4.1.0",
    "connect": "3.6.6",
    "eslint": "7.15.0",
    "eslint-plugin-vue": "7.2.0",
    "lint-staged": "10.5.3",
    "runjs": "4.4.2",
    "sass": "1.32.0",
    "sass-loader": "10.1.0",
    "script-ext-html-webpack-plugin": "2.1.5",
    "svg-sprite-loader": "5.1.1",
    "vue-template-compiler": "2.6.12",
    "vue-loader": "^15.9.5",
    "@efox/emp-cli": "1.8.0",
    "@efox/emp-vue2": "latest"
  },
  "engines": {
    "node": ">=8.9",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}

emp-config.js
const path = require('path')
const {VueLoaderPlugin} = require('vue-loader')
//
const ProjectRootPath = path.resolve('./')
// const packagePath = path.join(ProjectRootPath, 'package.json')
// const {dependencies} = require(packagePath)
//
const {getConfig} = require(path.join(ProjectRootPath, './src/config'))
//
module.exports = ({config, env, empEnv}) => {
  const confEnv = env === 'production' ? 'prod' : 'dev'
  const conf = getConfig(empEnv || confEnv)
  console.log('config', conf)
  //
  const srcPath = path.resolve('./src')
  config.entry('index').clear().add(path.join(srcPath, 'main1.js'))
  //
  config.resolve.alias.set('vue', '@vue/runtime-dom')
  config.plugin('vue').use(VueLoaderPlugin, [])
  config.module
    .rule('vue')
    .test(/\.vue$/)
    .use('vue-loader')
    .loader('vue-loader')
  //
  const host = conf.host
  const port = conf.port
  const projectName = 'vueComponents'
  const publicPath = conf.publicPath || 'dist'
  config.output.publicPath(publicPath)
  config.devServer.port(port)
  //
  config.plugin('mf').tap(args => {
    args[0] = {
      ...args[0],
      ...{
        name: projectName,
        library: {type: 'var', name: projectName},
        filename: 'emp.js',
        remotes: {
          empReactBase: 'empReactBase',
        },
        exposes: {
          './Content.vue': './src/components/Content',
        },
        /* shared: {
          ...dependencies,
        }, */
      },
    }
    return args
  })

  config.resolve.alias
  .set('vue$', 'vue/dist/vue.esm.js')
  .clear()

  //
  config.plugin('html').tap(args => {
    args[0] = {
      ...args[0],
      ...{
        title: 'EMP Vue Components',
        files: {
          js: ['http://localhost:8001/emp.js','http://code.jquery.com/jquery-1.9.1.min.js'

          ],
        },
      },
    }
    return args
  })
}

**Comment by flyyuan** [comment]
发一下你的项目，传到 GitHub

**Comment by longkehuawei** [comment]
用demo就行了，公司不准上传东西，脚手架搭建的vue工程好像就报这个错误，emp版本"version": "1.6.17",
{
"name": "hello",
"version": "0.1.0",
"private": true,
"scripts": {
"serve": "vue-cli-service serve",
"build": "vue-cli-service build",
"dev": "emp dev",
"build": "emp build --env prod",
"start": "emp serve",
"stat": "emp build --analyze",
"emp": "emp",
"lint": "vue-cli-service lint"
},
"dependencies": {
"core-js": "^3.6.5",
"vue": "^2.6.11"
},
"devDependencies": {
"@vue/cli-plugin-babel": "~4.5.0",
"@vue/cli-plugin-eslint": "~4.5.0",
"@vue/cli-service": "~4.5.0",
"babel-eslint": "^10.1.0",
"eslint": "^6.7.2",
"eslint-plugin-vue": "^6.2.2",
"vue-template-compiler": "^2.6.11",
"@efox/emp-cli": "latest",
"@efox/emp-vue2": "latest"
},
"eslintConfig": {
"root": true,
"env": {
"node": true
},
"extends": [
"plugin:vue/essential",
"eslint:recommended"
],
"parserOptions": {
"parser": "babel-eslint"
},
"rules": {}
},
"browserslist": [
"> 1%",
"last 2 versions",
"not dead"
]
}

**Comment by longkehuawei** [comment]
> 发一下你的项目，传到 GitHub

https://github.com/lanxingmo/hello-dev ，麻烦帮我看下
