### ISSUE TITLE
nuxt可以使用么？

### ISSUE THREAD

**Issue by a1285771357** [efoxTeam/emp#12]
我想在nuxt中使用如何实现呢

**Comment by ckken** [comment]
SSR 静态部分可以 服务直出部分还在探索 可以一起推进下

**Comment by trsoliu** [comment]
+1

**Comment by ckken** [comment]
升级到 webpack5 都支持（ssr 需要支持实现 steam import ，后续会考虑是否开源，目前社区都是闭源状态）
