### ISSUE TITLE
emp能够替代乾坤开发？

### ISSUE THREAD

**Issue by node-rookie** [efoxTeam/emp#120]
目前项目使用乾坤做开发，基于基座应用的模式，emp是去中心化的方式，所以有点困惑，使用emp如何实现乾坤的基座模式，如何实现子应用之间的无缝切换，应用与应用之间如何通信，共享状态，使用emp感觉不能很好的满足把一个大型应用拆分成多个子应用然后组合在一起，像同一个应用一样的使用体验

**Comment by ckken** [comment]
路由为引导 组件模块为 页面单元即可
