### ISSUE TITLE
vue3-base 如何给 vue3-project 传值呢

### ISSUE THREAD

**Issue by djdeo** [efoxTeam/emp#13]
如题：vue3-base 如何给 vue3-project 传值， 或者共享状态呢

demo里的 INC 按钮 能不能同时增加 两个项目的值呢

**Comment by flyyuan** [comment]
回答问题1，直接通过 props 和 attirs 都可以给 vue3-project 传值，传值和本地项目一致。共享状态可以使用同一个状态管理。
回答问题2，可以的，但是不建议这样做

**Comment by ckken** [comment]
这个可以close?
