### ISSUE TITLE
怎样把react组件嵌入Vue主工程路由下面

### ISSUE THREAD

**Issue by longkehuawei** [efoxTeam/emp#130]
主项目是vue ，子项目是react，怎样把react组件嵌入Vue主工程路由下面

**Comment by flyyuan** [comment]
![image](https://user-images.githubusercontent.com/19996552/114516145-b06a6e00-9c6f-11eb-8ea6-38c8b4988804.png)
可以参考下例子

**Comment by longkehuawei** [comment]
例子没有用到路由呀

**Comment by longkehuawei** [comment]
嵌入进去是没问题，主要是想要react组件做vue子路由

**Comment by flyyuan** [comment]
建 vue 页面放 react 组件。路由是 vue 正常写法。

**Comment by longkehuawei** [comment]
用emp改造的工程，怎么支持svg呀
