### ISSUE TITLE
vue 集成emp  支持svg

### ISSUE THREAD

**Issue by longkehuawei** [efoxTeam/emp#132]
vue 集成emp 在哪里配置   
config.module
      .rule('svg')
      .exclude.add(resolve('src/assets/icons'))
      .end()
    config.module
      .rule('icons')
      .test(/\.svg$/)
      .include.add(resolve('src/assets/icons'))
      .end()
      .use('svg-sprite-loader')
      .loader('svg-sprite-loader')
      .options({
        symbolId: 'icon-[name]'
      })
      .end()
emp-config.js 好像不能配置

**Comment by flyyuan** [comment]
相同 issue :https://github.com/efoxTeam/emp/issues/108

**Comment by ckken** [comment]
@flyyuan 看看有没有时间搞个vue的 demo

**Comment by flyyuan** [comment]
1

**Comment by flyyuan** [comment]
Vue 使用 svg 例子

**Comment by longkehuawei** [comment]
这个配置不起作用

**Comment by longkehuawei** [comment]
用的是我这边用的是svg-sprite-loader

**Comment by fengming312** [comment]
同样有这个问题，配置svg-sprite-loader不起作用

**Comment by fengming312** [comment]
> 用的是我这边用的是svg-sprite-loader

const svgRule = config.module.rule('svg')
  svgRule.uses.clear()
  svgRule
    .use('svg-sprite-loader')
    .loader('svg-sprite-loader')
    .options({
      symbolId: 'icon-[name]'
    })

这样写有效果
