### ISSUE TITLE
请问emp有什么好的方案做到数据状态共享，某一个状态更新，其他app自动更新

### ISSUE THREAD

**Issue by ChestnutsRiver** [efoxTeam/emp#138]

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/blob/94c9298dfe9c87913a0e0cb9fac2ec403a985a1c/projects/antd-base/src/App.tsx#L14

**Comment by ChestnutsRiver** [comment]
> https://github.com/efoxTeam/emp/blob/94c9298dfe9c87913a0e0cb9fac2ec403a985a1c/projects/antd-base/src/App.tsx#L14

vue项目呢？我用vuex，两个app可以实现，三个就不行了
