### ISSUE TITLE
接入现有项目报错

### ISSUE THREAD

**Issue by carlSunLiang** [efoxTeam/emp#14]
UnhandledPromiseRejectionWarning: Error: Compiling RuleSet failed: Unexpected property test in condition

![image](https://user-images.githubusercontent.com/8129970/99358787-fbfb3480-28e8-11eb-97e8-ed436b8c49d1.png)

**Comment by ckken** [comment]
可否开放代码看看

**Comment by carlSunLiang** [comment]
这是我们公司项目，没办法开放呀，能不能给一个完整项目的案例呀。

**Comment by carlSunLiang** [comment]
> 可否开放代码看看

这是我们公司项目，没办法开放呀，能不能给一个完整项目的案例呀。

**Comment by ckken** [comment]
今天帮另外的部门接入EMP也遇到这个问题 可以尝试把 
package.json 的下面几个依赖去掉试试
```json
    "@vue/cli-plugin-eslint": "^4.5.8",
    "@vue/cli-plugin-router": "^4.5.8",
    "@vue/cli-plugin-vuex": "^4.5.8",
    "@vue/cli-service": "^4.5.8",
```

**Comment by carlSunLiang** [comment]
> 今天帮另外的部门接入EMP也遇到这个问题 可以尝试把
> package.json 的下面几个依赖去掉试试
> 
> ```json
>     "@vue/cli-plugin-eslint": "^4.5.8",
>     "@vue/cli-plugin-router": "^4.5.8",
>     "@vue/cli-plugin-vuex": "^4.5.8",
>     "@vue/cli-service": "^4.5.8",
> ```

好的，咱们文档啥时候发出来呀。这么优秀框架没有完备的文档不容易推广。

**Comment by ckken** [comment]
有时是 webpack 4 切换到 webpack5 导致的插件冲突问题 需要实战才知道  你看看行不行 feedback下

**Comment by Asarua** [comment]
解决了吗。我也有这问题。

**Comment by ckken** [comment]
> 解决了吗。我也有这问题。
删除下面依赖
```
    "@vue/cli-plugin-eslint": "^4.5.8",
    "@vue/cli-plugin-router": "^4.5.8",
    "@vue/cli-plugin-vuex": "^4.5.8",
    "@vue/cli-service": "^4.5.8",
```
