### ISSUE TITLE
When I use EMP to initialize a project, I encounter the following error. How can I solve it

### ISSUE THREAD

**Issue by webxmsj** [efoxTeam/emp#141]
![image](https://user-images.githubusercontent.com/40289489/116836657-ef9a3800-abf9-11eb-9589-906f5135d971.png)

**Comment by flyyuan** [comment]
Update the Node version to 12.10.0 or higher or update the @efox/emp-cli version to 1.8.19.
If you are using npx, just re-execute.

**Comment by flyyuan** [comment]
Update the Node version to 12.10.0 or higher or update the @efox/emp-cli version to 1.8.19.
If you are using npx, just re-execute. 
[](https://github.com/efoxTeam/emp/commit/30502b4f20ac64aa086d7dd3c92d0ebe9535c7a9#diff-bfc692c21efb8fc4596845bdd41d851addc4c5c982c2228217ca7fc5405392e0R10)
