### ISSUE TITLE
升级至1.8.19版本报babel信息

### ISSUE THREAD

**Issue by GaryHjy** [efoxTeam/emp#143]
## 问题
升级至1.8.19版本报babel信息

## 描述
版本：1.8.19

信息如图：
![image](https://user-images.githubusercontent.com/32995274/117529962-48f4d380-b00d-11eb-8992-82ccea9dfb19.png)

**Comment by GaryHjy** [comment]
只是升级了emp/cli 为1.8.19，npm run serve/build 就报babel信息，1.8.18为正常

**Comment by flyyuan** [comment]
麻烦提供一个可以复现的项目或者是 emp-config

**Comment by GaryHjy** [comment]
不知道为啥没出现报错了。可以关闭issue了
