### ISSUE TITLE
基于vue3.0子应用使用vuex，报错

### ISSUE THREAD

**Issue by balsampearshen** [efoxTeam/emp#144]
![image](https://user-images.githubusercontent.com/3590216/117640085-3c13e380-b1b7-11eb-85fb-1dd71ef86e1b.png)
子应用某个页面使用了vuex，实现状态管理，子应用单独运行正常，主应用引用了该页面后报错，经调试发现 useStore()方法返回的对象为undefined
![image](https://user-images.githubusercontent.com/3590216/117640266-6cf41880-b1b7-11eb-8825-0e9215d30b48.png)

**Comment by flyyuan** [comment]
请放一个可复现的 demo repo
