### ISSUE TITLE
根据文档初始化项目报错

### ISSUE THREAD

**Issue by airkingZy** [efoxTeam/emp#145]
使用@efox/emp-cli 创建了一个react一个vue2例子之后，按照 [《Vue和React项目如何互相远程调用》](https://github.com/efoxTeam/emp/wiki/%E3%80%8AVue%E5%92%8CReact%E9%A1%B9%E7%9B%AE%E5%A6%82%E4%BD%95%E4%BA%92%E7%9B%B8%E8%BF%9C%E7%A8%8B%E8%B0%83%E7%94%A8%E3%80%8B) 配置相关文件，然后启动，分别出现以下错误，图1是react端的错误，图2是vue2
![image](https://user-images.githubusercontent.com/24963857/117771708-f4e62b00-b268-11eb-80ca-ca10430dfb01.png)
![image](https://user-images.githubusercontent.com/24963857/117771837-1cd58e80-b269-11eb-8949-cec088b52043.png)
`Repo`: https://github.com/airkingZy/empExample
thanks

**Comment by airkingZy** [comment]
@ckken
都装了,node_module没有找到vuera这个，用cli生成的工程package.json也没有依赖这个vuera

**Comment by ckken** [comment]
demo 没包依赖

**Comment by airkingZy** [comment]
@ckken 我提供的repo demo没有依赖吗，我尝试了不用lerna去管理2个工程，单独用cli创建了2个独立项目（vue2和react）也是同样的问题
按
```

**Comment by panzhengtao** [comment]
没遇到过这个问题，可以试试单独安装一下vuera

**Comment by airkingZy** [comment]
![image](https://user-images.githubusercontent.com/24963857/117964055-bf6a3c00-b353-11eb-8c0c-42dfd70a25d3.png)
repo: https://github.com/airkingZy/emp-vue-example (vue-demo)
          https://github.com/airkingZy/emp-react-example (react-demo)
出现问题的是 react那个，是上面报告的问题产生后,重新init了2个项目，然后运行起来报错缺了什么，我手动用yarn去一个个安装的

**Comment by airkingZy** [comment]
还有个问题
![image](https://user-images.githubusercontent.com/24963857/117964823-aa41dd00-b354-11eb-9365-7788e6a70a38.png)
项目按新的引入方式也会报错，改回旧的就没问题
还有在emp.config.js文件里
``` 
 shared: {...dependencies}
```
写上这个，为什么还会在react提示缺少vue，在vue提示缺少react-dom，react
vuera 这个包不应该是在cli里面生成模版的时候在package.json写上，或者在@emp的包里面作为一个前置的依赖吗？

**Comment by flyyuan** [comment]
vuera 这个包不是 emp 的一部分。需要手动安装

**Comment by flyyuan** [comment]
> 写上这个，为什么还会在react提示缺少vue，在vue提示缺少react-dom，react
> vuera 这个包不应该是在cli里面生成模版的时候在package.json写上，或者在@emp的包里面作为一个前置的依赖吗？

1.vuera 这个包不是 emp 的一部分。需要手动安装
2.需要互相调用，需要有 React 和 Vue 的 runtime

> ERROR in container entry ./configs/index[0]
> Module` not found: Error: Can't resolve 'src/configs/index'

是因为 src/configs/index 是空文件，删除即可
