### ISSUE TITLE
基站和业务站开发完毕以后，如何部署上线？

### ISSUE THREAD

**Issue by panzhengtao** [efoxTeam/emp#146]
已经开发完毕，现在不知道如何部署上线，想请问EMP大神是否有上线部署步骤的说明文档？小白还望多多指教，谢谢。。

**Comment by ckken** [comment]
@dragonkuang @doerme

**Comment by doerme** [comment]
构建后可以指定产物publish到npm。发布成功后使用unpkg等第三方cdn服务对npm资源进行访问即可。

npm发布:
https://docs.npmjs.com/cli/v7/commands/npm-publish

unpkg服务:
https://unpkg.com/

**Comment by dragonkuang** [comment]
emp项目默认打包生产的产物在dist目录，直接把dist文件发布就好了，可以说emp项目部署跟react/vue项目部署没什么差别，自己有服务器的话，直接nginx也行
