### ISSUE TITLE
使用脚手架创建的vue3-base，引入element-plus报错

### ISSUE THREAD

**Issue by 17610278281** [efoxTeam/emp#15]
您好，使用脚手架创建的vue3-base之后，引入element-plus时代码报错；
![image](https://user-images.githubusercontent.com/32235692/99667125-e3387d80-2aa6-11eb-9a96-99bc83b5dba1.png)
然后我尝试添加vue.config.js，但是发现yarn dev走的是“emp dev“的命令，不会走我自己创建的webpack规则，请问有没有稍微完整的项目？

**Comment by ckken** [comment]
> 您好，使用脚手架创建的vue3-base之后，引入element-plus时代码报错；
> ![image](https://user-images.githubusercontent.com/32235692/99667125-e3387d80-2aa6-11eb-9a96-99bc83b5dba1.png)
> 然后我尝试添加vue.config.js，但是发现yarn dev走的是“emp dev“的命令，不会走我自己创建的webpack规则，请问有没有稍微完整的项目？

可否提供demo

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/tree/main/projects/element-plus 尝试跑通ing

**Comment by 17610278281** [comment]
> https://github.com/efoxTeam/emp/tree/main/projects/element-plus尝试跑通ing

您好，我把您的demo下载下来跑了，我也把我写的代码尝试跑了，现在出现这个问题，初步怀疑是打包问题，也可能是element-plus的问题，请问您那里能跑通嘛？？
![image](https://user-images.githubusercontent.com/32235692/99761203-78cc1f80-2b30-11eb-90d0-74b1b23d5ade.png)

**Comment by 17610278281** [comment]
[dome.zip](https://github.com/efoxTeam/emp/files/5571333/dome.zip)
这是我的demo，在yarn之后运行yarn dev，就会出现上面的错误

**Comment by 17610278281** [comment]
> https://github.com/efoxTeam/emp/tree/main/projects/element-plus 尝试跑通ing

麻烦大佬百忙之中给看一下，万分感谢！！！

**Comment by 17610278281** [comment]
在检查哪个包出现的的定位，没有在代码里发现这个有引这个文件
![Uploading image.png…]()

**Comment by 17610278281** [comment]
![image](https://user-images.githubusercontent.com/32235692/99761943-563b0600-2b32-11eb-8467-cb6dfcf06e67.png)

**Comment by ckken** [comment]
还在测试 跑通 告诉你

**Comment by ckken** [comment]
fix: https://github.com/efoxTeam/emp/commit/cee3798295f34ff32acdb964379510a71ea98b66
