### ISSUE TITLE
1.8.19版本打包时打印出babel提示信息

### ISSUE THREAD

**Issue by yangzi0914** [efoxTeam/emp#153]
打包提示如截图所示：

![image](https://user-images.githubusercontent.com/22220041/118782091-525d2600-b8c0-11eb-89f2-93eee1aaf77b.png)

在@babel/preset-env的配置项中增加loose: true，提示信息才会消失，修改如截图所示：

![image](https://user-images.githubusercontent.com/22220041/118782519-c4356f80-b8c0-11eb-8d0b-7e6c938baf22.png)

**Comment by ckken** [comment]
新装的babel 导致的问题 在看如何处理

**Comment by ckken** [comment]
fixed it https://github.com/efoxTeam/emp/commit/e9f3305556048eaa2c5797e61a411180519ac3ca

**Comment by flyyuan** [comment]
更新版本到  "@efox/emp-cli": "1.8.20"
https://github.com/efoxTeam/emp/releases/tag/v1.8.20
