### ISSUE TITLE
开发时禁用progress的问题

### ISSUE THREAD

**Issue by aov2005** [efoxTeam/emp#155]
https://github.com/efoxTeam/emp/blob/e9f3305556048eaa2c5797e61a411180519ac3ca/packages/emp-cli/bin/emp.js#L62

似乎没传入值，应该改为下面的
```javascript
.option('-ps, --progress <b>', '显示进度 默认为 true') 
```

还有在低端电脑的window 7 下的cmd里，webpack会输出打包信息然后clean控制台，再更新进度条，但是这个操作很花时间，导致npm run dev的时候时长可能为10分钟甚至更久，所以想禁用进程显示的需求

**Comment by ckken** [comment]
fixed it https://github.com/efoxTeam/emp/commit/fe034d74aa1c6036222232364d21cfe125062524
