### ISSUE TITLE
用emp-init生成了两个vue2的demo，引用报错

### ISSUE THREAD

**Issue by miskying** [efoxTeam/emp#159]
![image](https://user-images.githubusercontent.com/26668165/120166493-35fda980-c22f-11eb-961f-cf612fb24713.png)
![image](https://user-images.githubusercontent.com/26668165/120166633-5e85a380-c22f-11eb-9f10-412b015add44.png)

照着掘金上的文章写的
A引用B的组件或者B引用A组件都会报这个错

大佬们抽几分钟跑跑看？

项目地址：https://github.com/miskying/emp-test1.git

**Comment by ckken** [comment]
判断变量没了 这么神奇？

**Comment by flyyuan** [comment]
请更新到 emp-cli 的 1.8.23 版本，
init 分别使用 vue2-base 和 vue2-project

**Comment by ckken** [comment]
怎么解决的

**Comment by flyyuan** [comment]
@ckken 
1.可能时 mf 对在 html-webpack-plugin file 上引入的文件有兼容性问题。
`
    config.plugin('html').tap(args => {
        args[0] = {
            ...args[0],
            ...{
                // head 的 title
                title: 'base',
                // 远程调用项目的文件链接
                files: {
                    js: ['http://localhost:8007/emp-com.js']
                }
            }
        };
        return args;
    });
`
这种方式引入会导致 !== 报错

解决方法： 
`
 remotes: {
                    'xxx': 'xxxx@http://xxxxx/emp.js'
                },
`

2. vue-loader 对在顶部 import 远程模块可能导致 call 报错
解决方法：
`
  components: {
    Xxxxxx: () => import("xxxx"),
  },
`
