### ISSUE TITLE
base没有的component，project里如何捕捉异常？

### ISSUE THREAD

**Issue by aov2005** [efoxTeam/emp#16]
目前看到的是报错

`throw new Error('Module "' + module + '" does not exist in container.');`

在bootstrap.js里catch不到

```
try{
  const Abc = defineAsyncComponent(() => import('vue3Components/abc'))
  app.component('abc-element', Abc)
}catch(err){
  console.log(err)
}
```

**Comment by ckken** [comment]
可否说说你的需求

**Comment by ckken** [comment]
组件加载放到了 外部 webpack://@empvue3/base/webpack/container-entry 可以说说你的业务场景

**Comment by aov2005** [comment]
场景是
一个工厂base，多个消费者project，base提供公共依赖，并且可以通过接口动态注册import project，base渲染出所有project组件，如果接口返回了，但是没project，需要显式的报错给访问base的前端用户

**Comment by ckken** [comment]
......看看可能弄个demo

**Comment by aov2005** [comment]
可能方向错了，再研究下吧，看看怎么把project里的组件单独编译出来存数据库里，base拉取的时候动态定义component
