### ISSUE TITLE
第三库版本不一致问题

### ISSUE THREAD

**Issue by wuweikd** [efoxTeam/emp#166]
描述：现有基站的 antd 版本为4.1.1 ，基站二次封装了Form表单供给A，B，C项目使用。现在antd4.6 出了一个新组件 ，A项目想使用。 现发现升级A项目antd为4.6后，基站的4.1.1的Form表单语法与4.6语法不兼容。

问：如何合理的处理此版本的问题，使得改动成本较小。

**Comment by ckken** [comment]
理想的情况是基站共享出来 可以把代码贴出来看看报错

**Comment by wuweikd** [comment]
> 理想的情况是基站共享出来 可以把代码贴出来看看报错

这种情况下，基站不能改动，毕竟破坏性改动会影响到所有的项目，我最终放弃升级antd了。
