### ISSUE TITLE
vue2代码中引入图片，无法修改output.publicPath

### ISSUE THREAD

**Issue by riceapple** [efoxTeam/emp#169]
在子站的emp-config.js中指定了http://XXXXX的output.publicPath，打包出来的文件还是相对主站域名的相对地址，没有把output.publicPath打包成http://XXXX+文件地址的形式

**Comment by ckken** [comment]
有 demo 吗

**Comment by riceapple** [comment]
<img width="482" alt="企业微信截图_92864a49-bc0f-4f2a-a291-08978ec9aaf1" src="https://user-images.githubusercontent.com/8100195/121459265-828a7700-c9dd-11eb-9a8f-388d40dad705.png">
<img width="597" alt="企业微信截图_6eb6e0e1-71f9-4689-97af-7f2b5a38565a" src="https://user-images.githubusercontent.com/8100195/121459275-85856780-c9dd-11eb-9f86-9d1ab2ac843f.png">
配置了output.publicPath 文件打包出来的路径,最新版本没有把publicPath拼上去,
