### ISSUE TITLE
emp 文件指纹策略问题

### ISSUE THREAD

**Issue by riceapple** [efoxTeam/emp#171]
使用emp将原来项目拆分为多个子项目，有一些文件的文件名重复，打包出来的文件只保留8位文件hash，无法体现出文件不同，导致子站加载顺序不同，不会加载同名文件，但文件内部的export方法不一致，出现undefined报错

**Comment by flyyuan** [comment]
麻烦发一个可以复现 repo

**Comment by riceapple** [comment]
> 麻烦发一个可以复现 repo
能否有讨论群让我加入一下，或者即时通讯工具

**Comment by ckken** [comment]
我们有微信群啊

**Comment by riceapple** [comment]
> 我们有微信群啊

过期了吧。加不了
