### ISSUE TITLE
怎么改变antd默认主题色？

### ISSUE THREAD

**Issue by wzwlhc** [efoxTeam/emp#174]

**Comment by flyyuan** [comment]
见 antd 文档
https://ant.design/docs/react/customize-theme-cn

**Comment by wzwlhc** [comment]
> 见 antd 文档
> https://ant.design/docs/react/customize-theme-cn
写在emp-config.js里面, 然后用config.merge(less配置)
  const lessConfig = {
    module: {
      rule: {
        less: {
          test: lessRegex,
          exclude: lessModuleRegex,
          use: {
            less: {
              loader: require.resolve('less-loader'),
              options: {
                lessOptions: {
                  modifyVars: {
                    'primary-color': '#FFBB41',
                    'link-color': '#FFBB41',
                    'border-radius-base': '2px',
                  },
                  javascriptEnabled: true,
                },
              },
            },
          },
        },
      },
    },
  }
  config.merge(lessConfig)

**Comment by ckken** [comment]
这个解决了吗？  晚点写篇 1.8 的配置方案

**Comment by wzwlhc** [comment]
> 这个解决了吗？ 晚点写篇 1.8 的配置方案

解决了哈  详情请见上面
