### ISSUE TITLE
配置了output.publicPath 文件打包出来的路径,最新版本没有把publicPath加到资源文件地址上

### ISSUE THREAD

**Issue by riceapple** [efoxTeam/emp#175]
<img width="482" alt="企业微信截图_92864a49-bc0f-4f2a-a291-08978ec9aaf1" src="https://user-images.githubusercontent.com/8100195/121459265-828a7700-c9dd-11eb-9a8f-388d40dad705.png">
<img width="597" alt="企业微信截图_6eb6e0e1-71f9-4689-97af-7f2b5a38565a" src="https://user-images.githubusercontent.com/8100195/121459275-85856780-c9dd-11eb-9f86-9d1ab2ac843f.png">
配置了output.publicPath 文件打包出来的路径,最新版本没有把publicPath拼上去,

最后降级为如下版本
  "@efox/emp-cli": "^1.4.0",
   "@efox/emp-vue2": "^1.2.0",

**Comment by ckken** [comment]
https://juejin.cn/post/6974641180592046116/
