### ISSUE TITLE
base把第三方组件库放组件里暴露出去，project去获取组件的时候获取到的是未编译的原dom，这个是需要在哪里配置嘛？

### ISSUE THREAD

**Issue by zxgMaster** [efoxTeam/emp#18]
base：
![image](https://user-images.githubusercontent.com/32235692/100714646-06412680-33f1-11eb-88df-3b11edb07032.png)

project：
![image](https://user-images.githubusercontent.com/32235692/100714724-1ce77d80-33f1-11eb-9b8a-d6ccdf8d9185.png)
![image](https://user-images.githubusercontent.com/32235692/100714738-253fb880-33f1-11eb-98cd-6db7b04ad368.png)
![image](https://user-images.githubusercontent.com/32235692/100714778-32f53e00-33f1-11eb-832e-a630948a2f1b.png)

完全没有显示出来。。。
![image](https://user-images.githubusercontent.com/32235692/100714812-3d173c80-33f1-11eb-9c29-d1298589c48a.png)

求大佬看一下，是不是因为未编译的原因呢？

**Comment by ckken** [comment]
可否提供一个完整的demo 或者 codepen

**Comment by flyyuan** [comment]
在 emp.config.js 里配置对应需要暴露的组件了么？
例如：
```js
  exposes: {
          './Content': './src/components/Content',
          './Button': './src/components/Button',
        },
```

**Comment by 17610278281** [comment]
配置了，就是这个content组件，在父项目的content组件里面写一个<el-button></el-button>,  在子项目去引入content之后，显示的就是<el-button>，没有编译成原始dom

**Comment by flyyuan** [comment]
项目的 Reop 发一下？

**Comment by 17610278281** [comment]
> 可否提供一个完整的demo 或者 codepen


[子项目.zip](https://github.com/efoxTeam/emp/files/5633419/default.zip)
[父项目.zip](https://github.com/efoxTeam/emp/files/5633420/default.zip)

其中是在父项目中的content组件写了个<el-button>, 然后在子组件中引入content组件，没有编译

**Comment by 17610278281** [comment]
> 项目的 Reop 发一下？

发了，大佬

**Comment by flyyuan** [comment]
```
const { components } = require(path.join(ProjectRootPath, './src/components'))
 exposes: {
          ...components
        },
```
这样是直接解构是不允许的哈。
需要一个个组件对应expose
```
       // 需要暴露的东西
         exposes: {
           // 别名:组件的路径
            './Content': './src/components/Content',
            './Button': './src/components/Button'
}
```

**Comment by 17610278281** [comment]
> ```
> const { components } = require(path.join(ProjectRootPath, './src/components'))
>  exposes: {
>           ...components
>         },
> ```
> 
> 这样是直接解构是不允许的哈。
> 需要一个个组件对应expose
> 
> ```
>        // 需要暴露的东西
>          exposes: {
>            // 别名:组件的路径
>             './Content': './src/components/Content',
>             './Button': './src/components/Button'
> }
> ```

好的，我按照规范的写了，但是似乎还是没有编译这个el-button
![image](https://user-images.githubusercontent.com/32235692/100960451-43292c80-355b-11eb-9c95-0f3bd173ffba.png)
![image](https://user-images.githubusercontent.com/32235692/100960470-4e7c5800-355b-11eb-9b93-444358104cc2.png)

**Comment by flyyuan** [comment]
与 components 的解构无关。
我刚刚跑过你的项目，expose 出去的第三方组件没有被编译。
这是个 bug，可能会在下一个版本修复。
感谢您的反馈～ @17610278281

**Comment by 17610278281** [comment]
> 与 components 的解构无关。
> 我刚刚跑过你的项目，在Vue3下 expose 出去的第三方组件没有被编译。
> 这是个 bug，可能会在下一个版本修复。
> 感谢您的反馈～ @17610278281

好的，那等您改好之后，百忙之中给我说一下

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/101119606-a8961f80-3626-11eb-8acc-ae937bc0c0a9.png)
![image](https://user-images.githubusercontent.com/3890513/101119620-b350b480-3626-11eb-9e5d-54bf168ec6fc.png)
感觉是vue3问题 vue2 demo 更新上去没问题

**Comment by 17610278281** [comment]
啊，那vue3没有别的解决方法了嘛？

**Comment by DevilLeven** [comment]
不仅仅是第三方组件不被编译，在expose出去的组件里，只要加载其他的组件都不会被编译
![image](https://user-images.githubusercontent.com/21081386/101334823-54ec3600-38b3-11eb-9738-c434e9da6eb2.png)

**Comment by ckken** [comment]
目测是 `defineAsyncComponent` 的问题 回头看看

**Comment by 17610278281** [comment]
> 不仅仅是第三方组件不被编译，在expose出去的组件里，只要加载其他的组件都不会被编译
> ![image](https://user-images.githubusercontent.com/21081386/101334823-54ec3600-38b3-11eb-9738-c434e9da6eb2.png)

我觉着你更新一下cli的版本吧，我这边今天下午捣鼓了一下，el-button现在在vue3里面也正常编译了

**Comment by ckken** [comment]
@17610278281 你的依赖配置可以发一下吗

**Comment by ckken** [comment]
fixed it https://github.com/efoxTeam/emp/commit/d0b3d062685356c2ee009bcd13f15fd7bd5a3ac4

**Comment by ckken** [comment]
mf 增加 share 共享
```
...
shared: {
          vue: {eager: true, singleton: true, requiredVersion: '^3.0.2'},
        },
...
```

**Comment by flyyuan** [comment]
如果是 project 项目调用 base 项目里包含第三方组件库的组件，需要进行三步：
1. 需要 base 项目将 第三方组件库 通过 emp-config.js 的 expose 暴露
2. project 项目引入 base 通过 expose 暴露的第三方组件库依赖
3. project 项目和 base 项目一样引入第三方组件库（注意：引入的是base expose 出来的第三方组件库依赖）

具体例子可以看： 
element-plus-base:
https://github.com/efoxTeam/emp/tree/main/projects/element-plus-base
element-plus-project:
https://github.com/efoxTeam/emp/tree/main/projects/element-plus-project
