### ISSUE TITLE
spelling  errors in English Doc

### ISSUE THREAD

**Issue by anprettyboy** [efoxTeam/emp#187]
FAQ
Q: How share Vue dependencie ?

dependencie好像少一个字母s

**Comment by flyyuan** [comment]
fix in 
https://github.com/efoxTeam/emp/commit/fee72ca90f11f2b2ed535cf32171e8e2ca4f6856
https://github.com/efoxTeam/emp/commit/bbad6e72c2a7dce783a9a63a369df8fa243eb545
