### ISSUE TITLE
暴露配置信息

### ISSUE THREAD

**Issue by 17610278281** [efoxTeam/emp#19]
大佬，是否可以把这个config暴露出来，跟vue.config.js里配置内容一样配置？
![image](https://user-images.githubusercontent.com/32235692/100719704-f1b45c80-33f7-11eb-8ee4-61f6a42afac3.png)

**Comment by flyyuan** [comment]
1. 该 config 已经是处于暴露的状态，可以修改里面对象达到你的目的。
2. 可以不使用默认 config，去掉 withFrameWork()，重新配置。
3. vue.config.js 是与该 config 不一样的。
4. 虽然与 vue.config.js 不一致，但是功能已经完全覆盖。

**Comment by ckken** [comment]
hello! 目前是用 https://github.com/neutrinojs/webpack-chain 作为配置库 所以如果想增加的配置 只需按照 webpack chain 的规范就可以

**Comment by 17610278281** [comment]
收到，大佬们，我是这配一下
