### ISSUE TITLE
项目本地运行提示 Invalid Host header

### ISSUE THREAD

**Issue by yellowbeee** [efoxTeam/emp#196]

**Comment by yellowbeee** [comment]
设置 `config.devServer.allowedHosts` 解决

**Comment by ckken** [comment]
提个 pr https://github.com/efoxTeam/emp/blob/main/packages/emp-cli/webpack/config/devServer.js

**Comment by ckken** [comment]
fixed it https://github.com/efoxTeam/emp/pull/199
