### ISSUE TITLE
React babel 自定义配置的问题

### ISSUE THREAD

**Issue by byoungd** [efoxTeam/emp#201]
目前官方的cli配置里`babel/preset-react`的引入方法是通过 `require('@babel/preset-react').default`

如果想要更改 preset-react 的配置项的以使用React17的jsx转换语法的话 需要将该配置改为 
```
[
        require('@babel/preset-react').default,
        {
          runtime: 'automatic',
        },
]
```

emp.config.js 中通过 config.module tap的方式去修改该项时需要先将原来的配置从数组里删除，但是require的方式给类型判断带来了麻烦。

请问是否有更便捷的方式让用户自定义babel的相关配置？

**Comment by ckken** [comment]
可以尝试重写 https://github.com/efoxTeam/emp/blob/main/packages/emp-frameworks/react/index.js 然后导入到项目

**Comment by ckken** [comment]
回头升级下 插件 默认支持

**Comment by ckken** [comment]
https://zh-hans.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/128290653-302bf771-1459-497a-95f0-fe1c9bec6820.png)

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/commit/58f26436399ad95ac7e7fc6392a9b5864a6169dc
