### ISSUE TITLE
esbuild-react-demo 控制台过一段时间会出现 WebsocketClient 错误 之后的热更新就失效了需要手动刷新页面

### ISSUE THREAD

**Issue by byoungd** [efoxTeam/emp#202]
WebsocketClient.js?3719:16 WebSocket connection to 'ws://localhost:8000/sockjs-node' failed: 
WebsocketClient @ WebsocketClient.js?3719:16
react_devtools_backend.js:2574 [webpack-dev-server] Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}

控制台刷新页面后通过console.time测试时间间隔大约为 141492.79907226562 ms

出现这个错误之后页面的热更新就失效了 需要手动刷新页面 过一段时间之后又会出现该错误导致进入循环 非常影响开发体验

**Comment by ckken** [comment]
esbuild 跟 webpack 融合 并不好 可以看看 swc 的版本 验证到项目有效

**Comment by byoungd** [comment]
> esbuild 跟 webpack 融合 并不好 可以看看 swc 的版本 验证到项目有效

也就是说该问题应该 esbuild和webpack 结合的问题 和emp本身是无关的

**Comment by ckken** [comment]
会有各种问题 如无法构建CJS 等

**Comment by byoungd** [comment]
> 会有各种问题 如无法构建CJS 等

SWC相对于esbuild是相对成熟一些吗 是否可以用于生产环境了？
