### ISSUE TITLE
[URL] Fix link for demo React 17

### ISSUE THREAD

**Issue by bluezhan** [efoxTeam/emp#215]
![image](https://user-images.githubusercontent.com/16684336/134789961-ec270197-2f4a-473a-a3bf-c5c5d0c5446c.png)

Its https://github.com/efoxTeam/emp/tree/main/projects/react_diff17, then not https://github.com/efoxTeam/emp/blob/main/projects/react-diff17

**Comment by flyyuan** [comment]
Fixed, thanks
