### ISSUE TITLE
emp文档更新建议

### ISSUE THREAD

**Issue by wdlnydhcg** [efoxTeam/emp#219]
虽然从早早聊了解到emp，了解到yy做了这样一个微前端的框架，但是在网上能搜到的资料寥寥无几，无论是百度，还是谷歌，无论是油管还是B站，除了早早聊的两次的视频，我是没看到一个能叫做emp教程的微前端学习视频或教程了。
团队将文档都只放在github上，有没有考虑过国内有些地方是访问不了的情况？(不要说梯子就能解决，国内的网络有些地方是禁止访问这种境外网站)
就算是github上的文档，看过去也是一头雾水，除了一个gif的图搞明白了用个脚手架初始化项目外，其他的内容都不知道是干啥的。
指令插件开发指引？这些插件是干嘛的？我用来解决什么问题？怎么用？也没说明白。就一通安装。
框架配置插件列表？哎，几个404无用超链接放那好看些吗？
构建,emp多框架互调插件，这是些啥，一堆自己造的轮子，也没个说明。所谓的demo列表，就是一个安装了emp的最简单的页面。都搞明白写着文档的人，是写给谁看的？是给自己的吗？除了你自己，你看还有谁看得懂这文档。
最浅显的道理，写这种文档的人应该是以一个一问三不知的视角去看学的东西，而不是站在一个“知道者”的视角去写，而显然，emp的文档编辑者是后者。

**Comment by wdlnydhcg** [comment]
有点带着情绪写下这个issue，可能是因为，从早早聊那里听到比qiankun更好的微前端方案的时候期待值比较高，而查阅了一天的资料后却越来越失望的原因吧。感觉自己的一天都浪费在理解这该死的文档了。

**Comment by wdlnydhcg** [comment]
我认为，一个开源项目是不是坑，首先是看文档，一个连文档都维护不好的项目，能让人放心的入坑吗？国内qiankun文档已经这么烂了，但是有那么多人在钉钉里面回复大家的问题，并把问题进行总结，以及将问题的方案积累成demo，让大家去查看。emp却连一个基本的讨论群的二维码都维护不了。这样的一个现状，谁能用emp?谁敢用emp?把这种维护不了东西四处宣传，不仅浪费自己的时间，更是浪费带着好奇，想尝试的人的时间。

最后，我只想说一句，浪费别人的时间就是谋杀！！

**Comment by flyyuan** [comment]
正准备写实战类教程：
稍作预告:

1. 微前端概念
    1. 主流微前端实现
    2. 微拆分应用
        1. 后端：函数调用 -> 远程调用
        2. 前端：组件调用 -> 应用调用
    3. 为什么微前端会出现在Web 应用
        1. 后端解耦，前端聚合
        2. 大型项目降低心智负担
    4. 如何解构单体前端应用→EMP微组件
        1. 前端微服务化→ 微组件
        2. 独立开发
        3. 独立部署
        4. 不影响用户体验
    5. 设计理念
    6. 大型项目实战架构
2.  基于 EMP 微组件与微应用的 Vue 后台管理系统
    1. 微组件模式
        1. 快速创建微组件主工程
        2. 快速创建微组件
        3. 微前端主工程引入微组件
        4. 微组件直接互相通信
        5. 微组件独立部署与版本管理、配置自动化
    2. 微应用模式
        1. 快速创建微应用主工程
        2. 快速创建子应用
        3. 路由懒加载子应用
        4. 导航到特定的子应用
        5. 子应用直接互相通信与数据共享
        6. 微应用独立部署与版本管理、配置自动化
3.  基于 EMP 微组件的 H5 移动端项目
    1. EMP微组件项目间调用介绍
    2. EMP微组件动态化远程调用
    3. EMP微组件H5动态加载方案
    4. EMP微组件H5样式处理

**Comment by wdlnydhcg** [comment]
> 切换到 QQ 群 @flyyuan 方便新人加入 @wdlnydhcg 目前你们开发落地是基于什么框架 实现什么内容

qiankun,ERP

**Comment by ckken** [comment]
> > 切换到 QQ 群 @flyyuan 方便新人加入 @wdlnydhcg 目前你们开发落地是基于什么框架 实现什么内容
> 
> qiankun,ERP

可以把需求点列下 我们打算做小册子 会把需求考虑进去教程

**Comment by ckken** [comment]
还有目前qiankun cover不到的点也可以列列

**Comment by flyyuan** [comment]
@wdlnydhcg 现在QQ群人不多。但是可以先加我微信，进微信群；微信号 740004544

**Comment by wuweikd** [comment]
微信群 二维码就是个坑。

**Comment by ckken** [comment]
弄个了企业微信群 可以试试 不会过期那种

**Comment by wdlnydhcg** [comment]
> > > 切换到 QQ 群 @flyyuan 方便新人加入 @wdlnydhcg 目前你们开发落地是基于什么框架 实现什么内容
> > 
> > 
> > qiankun,ERP
> 
> 可以把需求点列下 我们打算做小册子 会把需求考虑进去教程

> 弄个了企业微信群 可以试试 不会过期那种

作为一个对emp完全不懂的小白，我有以下想了解的点
* 在老项目中，如何不用脚手架使用上emp(如何手动给老项目配置emp，逐步拆解)

* 在新项目中，如何从零搭建emp的项目（脚手架只是创建了一个配置了emp的项目，但是如何将多个项目串起来？）

* 如何从qiankun如何迁移emp？迁移中需要注意什么？有哪些坑？

* 看到emp可以搭建远程组件库，如何搭建？是否有案例代码参考？

* 在模块联邦中无基座的概念，但是我目前的项目是用qiankun搭的基座和子应用，如何迁移基座和子应用，能否给出类似的案例或者demo。最好是经典的ERP的通用模板项目。效果如下,我知道模块联邦中的思想和single-spa不一样，但是我当前的项目是用乾坤实现下面这种结构，但是如何用emp最低成本的改造呢？
![image](https://user-images.githubusercontent.com/17740155/137571479-0ca71e03-7a0c-44ad-a409-3ee53abcadfa.png)
