### ISSUE TITLE
Npm package item-generator4 style become abnormal when use emp build my project

### ISSUE THREAD

**Issue by Andrewuetyang** [efoxTeam/emp#226]
Submitted a demo to this repo's document mentioned  community group of enterprise wechat.(已提交一个demo，到企业微信群)  
Also, it can **reproduce easily** by use the npm package item-generator4 in your emp project.

**style abnormal like below:**

- **use emp**
<img width="899" alt="屏幕快照" src="https://user-images.githubusercontent.com/22719906/140249406-6ed9caa4-7775-4b9f-b16d-8cf15e970e7a.png">

- **use only webpack5**
<img width="969" alt="屏幕快照2" src="https://user-images.githubusercontent.com/22719906/140249423-365b52f4-dd9a-4adf-956f-0d3652958454.png">

**Comment by ckken** [comment]
群里好像有人解决了？

**Comment by Andrewuetyang** [comment]
> 群里好像有人解决了？

没有，群里那哥们儿没搞懂问题是什么，只是运行起来了（本来项目就能运行起来）。另外，我今天早上进一步定位到问题了，emp的Babel配置导致了我的这个问题，具体怎么改还得进一步看看，如果好改，不影响其他的话，我就提个PR

**Comment by Andrewuetyang** [comment]
该issue可以close了，基础配置还是不太好直接改源码，还是从业务配置利用webpack-chain的能力直接修改配置最佳。
