### ISSUE TITLE
Angular v11 support

### ISSUE THREAD

**Issue by Alexzjt** [efoxTeam/emp#23]
Angular v11: Experimental webpack 5 Support. Now, teams can opt-in to webpack v5. Currently, you could experiment with module federation.
Please add Angular v11 demo

**Comment by ckken** [comment]
angular 11 构建环境相对封闭、需要上module federation 可以考虑按照 https://github.com/module-federation/module-federation-examples/tree/master/angular11-microfrontends 来实现
