### ISSUE TITLE
react 模板引入vue2+ts 失败

### ISSUE THREAD

**Issue by Carl0608** [efoxTeam/emp#235]
我用emp init 创建了一个react 项目A  一个vue2+ts 模板B ，

我发现在react里面引入不成功

A项目的配置：

![a项目](https://user-images.githubusercontent.com/52045291/142234138-fe3a766c-6942-4de8-8d68-c082001bf096.png)

B项目的配置：
![B项目](https://user-images.githubusercontent.com/52045291/142234330-5da4657a-8567-4f69-b5be-a1f4a3e09442.png)

网上查找说要用vuera 包裹一下
![包裹](https://user-images.githubusercontent.com/52045291/142234506-6160e522-b3d0-4d73-9f65-6f653c81713a.png)
但是最后暴了一个很奇怪的错误
![错误](https://user-images.githubusercontent.com/52045291/142234687-b9f5fcdf-1b7c-4a29-b422-537cec5afeff.png)
是我的打开方式不对嘛？

**Comment by Carl0608** [comment]
项目里红色的报错只是eslint 的报错

**Comment by ckken** [comment]
emp 暂时不考虑 跨组件方案  目前综合评估有点违背 项目的统一性原则 可以考虑统一框架方式共享 达到的效果更佳
