### ISSUE TITLE
各应用之间相互引用，但某个应用停止服务是否导致其他应用报错？

### ISSUE THREAD

**Issue by viviScript** [efoxTeam/emp#236]
各个应用都有资源引用，但是当某个应用需要重新部署或停止使用时，其他与之关联的应用出现组件报错或者无法访问，这种情况该怎么处理呢

**Comment by viviScript** [comment]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/20518195/142385238-2b4005e0-d692-42bf-9cfa-997395abefab.png">

**Comment by ckken** [comment]
尝试加入 error boundary
