### ISSUE TITLE
ts

### ISSUE THREAD

**Issue by wzwlhc** [efoxTeam/emp#247]
你好 
问题如下：
1、emp-antd/base基站里面安装了antd，emp-antd/project项目里未安装  打包后生成的ts   ModalProps找不到 项目里面也必须安装antd吗？
代码如下： 
declare module '@emp-antd/base/components/common/crud/ModalForm' {  
     import { ModalProps } from 'antd/lib/modal/Modal'
     export interface ModalFormProps extends ModalProps {}
}
请问这种如何解决呢？

**Comment by ckken** [comment]
可以把需求列下 我们打算做2.0的种子项目
