### ISSUE TITLE
EMP2.0开发文档有误解

### ISSUE THREAD

**Issue by ghlds** [efoxTeam/emp#251]
module.exports={
   empShare: {
   name: 'microApp',
   remotes: {
     '@microHost': `microHost@http://localhost:8001/emp.js`,
   },
   exposes: {
     './App': './src/App',
   },
 👇👇👇👇👇👇👇👇👇👇👇👇这个地方介绍的是否有问题？shared应该只存在Module Feration？存在empShare里不起作用
   // 实现 Module Feration 与 shareLib 只能保留一个 
   shared: {
     react: {requiredVersion: '^17.0.1'},
     'react-dom': {requiredVersion: '^17.0.1'},
   },
 👆👆👆👆👆👆👆👆👆👆👆👆
   // 实现 emp share 的 三级共享模式 与 shared 只能保留一个,地址可以自行判断
   shareLib: {
     react: 'React@https://cdn.jsdelivr.net/npm/react@17.0.2/umd/react.development.js',
     'react-dom': 'ReactDOM@https://cdn.jsdelivr.net/npm/react-dom@17.0.2/umd/react-dom.development.js',
   }
   },
}

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/tree/next/projects/mf-app
