### ISSUE TITLE
关于babel.config.js的使用

### ISSUE THREAD

**Issue by DevilLeven** [efoxTeam/emp#26]
在 webpack 配置的源码里，如何更改`useBuiltIns` 为`usage`，
![image](https://user-images.githubusercontent.com/21081386/101885915-b6731400-3bd5-11eb-982f-b563466ddfde.png)

或者我们采用 `babel.config.js`
![image](https://user-images.githubusercontent.com/21081386/101885987-d73b6980-3bd5-11eb-8a04-fcb5b851b717.png)

**Comment by ckken** [comment]
+ 1. `usage` 目前还是实验选项 不推荐 
+ 2. 必须修改可以参考 `webpack-chain`
