### ISSUE TITLE
配置config.html后，config.externals 配置无效

### ISSUE THREAD

**Issue by doguya** [efoxTeam/emp#273]
1. 拉取 `vue-2-base` / `vue-2-project` 两个模板
2. 修改`vue-2-project` 下的 `emp-config.js`，修改 html.template 配置，如 `html: { template: 'template/index.html' }`
3. 再次进入project启动路径，提示错误：Vue is not defined

是否 `html` 与 `externals` 不能同时配置？

如果是的话，在配置了自定义html模板文件的情况下，如何实现
`{module: 'vue', global: 'Vue', entry: '...'}`
中的
`global: Vue`

**Comment by ckken** [comment]
有代码仓库吗

**Comment by ckken** [comment]
403

**Comment by doguya** [comment]
已设置为公开
