### ISSUE TITLE
安装 @efox/emp 时提示存在已废弃的包

### ISSUE THREAD

**Issue by typistZxd** [efoxTeam/emp#274]
在 [pnpm-lock.yaml](https://github.com/efoxTeam/emp/blob/next/pnpm-lock.yaml) 锁住了这些版本

 WARN  deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
 WARN  deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
 WARN  deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
 WARN  deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
 WARN  deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
 WARN  deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated

**Comment by ckken** [comment]
是 vue 还是？ 我试了下 好像没这个问题

**Comment by typistZxd** [comment]
通过pnpm安装的`@efox/emp`，安装过程会有提示，去[pnpm-lock.yaml](https://github.com/efoxTeam/emp/blob/next/pnpm-lock.yaml) 这里搜了下的确锁住了这些版本。

**Comment by typistZxd** [comment]
依赖版本问题还有 `@efox/eslint-config-vue`中的依赖的eslint是6.5.1，但业务中用的是eslint8，考虑是否升级

**Comment by ckken** [comment]
看看能否提个PR

**Comment by ckken** [comment]
可以详细描述下 我验证可行性

**Comment by ckken** [comment]
fixed it in `@efox/eslint-config-vue@2.0.1` update eslint 7
