### ISSUE TITLE
子应用切换为ESM模式下报错

### ISSUE THREAD

**Issue by zhongshankaka** [efoxTeam/emp#282]
Base应用也是有启动的，在默认的8001端口，然后子应用emp-config.js将target切换为"es2018"：
<img width="678" alt="image" src="https://user-images.githubusercontent.com/17596583/165048913-d58c7b71-efa4-4384-9f0d-82e5027cb7a9.png">

然后访问子应用报错：
![image](https://user-images.githubusercontent.com/17596583/165049044-d929833f-8958-4b6d-a87e-00250f009851.png)

**Comment by ckken** [comment]
你基站项目启动了吗

**Comment by zhongshankaka** [comment]
> 你基站项目启动了吗

启动了的，如果是用cdn加载依赖就没有问题。

**Comment by ckken** [comment]
fixed it in v2.2.0
