### ISSUE TITLE
打包部署时出现找不到组件问题

### ISSUE THREAD

**Issue by 924783180** [efoxTeam/emp#289]
Admin: 主服务
Base: 基础服务，用于分享公共方法或组件
site: 子服务

错误：
Admin -> exposes: {'./Share': './src/share'}, remotes: { '@Base': 'Base@./Base/emp.js' }

Base -> exposes: {'./Share': './src/share'},  remotes: { '@Admin': 'Admin@./emp.js' }

site -> remotes: { '@Base': 'Base@./Base/emp.js' }

这样一个组件的调用方式，导致site中使用 import Share from '@Base/Share'时发生错误

修改：
site -> remotes: {  '@Admin': 'Admin@./emp.js' }

此问题开发环境下不会出现，只有打包部署时会出现

**Comment by ckken** [comment]
可以提供用例代码 online
