### ISSUE TITLE
每次new GlobalStore()

### ISSUE THREAD

**Issue by codcer** [efoxTeam/emp#290]
store.ts 中 为啥每次new GlobalStore(),, 不应该是单实例吗? 但是跑debugger, 每次都会走很多变遍store的构造器. 这是性能开销吗?还是有意这样设计?

**Comment by ckken** [comment]
可以提供用例代码 online

**Comment by codcer** [comment]
class GlobalStore {
  constructor(){
       console.log('进来了’);  // 编译之后,会看到多次输出这个
  }

  /**
   * EMP Version
   * @default package version
   */
  public empPkg: pkgType = {dependencies: {}, devDependencies: {}, version: '2.0.0', name: ''}
  /**
   * 项目pkg信息
   */
  public pkg: pkgType = {dependencies: {}, devDependencies: {}, version: '0.0.0', name: ''}
  /**
   * 项目根目录绝对路径
   * @default process.cwd()
   */
  public root = process.cwd()
  /**
   * emp 内部根路径
   * @default path.resolve(__dirname, '../../')
   */
  public empRoot = path.resolve(__dirname, '../../')
