### ISSUE TITLE
请问如何在Vue3项目中 引入vue2的组件。vue2的组件依赖的第三方组件库 例如element-ui

### ISSUE THREAD

**Issue by sisiban0** [efoxTeam/emp#291]
我在项目例子中发现了Vue3使用vue2组件，但是vue2组件并没有依赖第三方库。
`// Vue2 组件`
`import Content from "@v2b/Content";`
`// Vue2 在 Vue3 运行的 HOC`
`import { Vue2InVue3 } from "@efox/emp-vuett";`
`// 让 Vue2 组件通过 emp-vuett 可以在 Vue3 上运行`
`// 传入 Vue2 组件和当前模板一个空div的id`
`const ContentInVue3 = Vue2InVue3(Content, "content");`

1. 我看vue3 里面是这样写的 但是@efox/emp-vuett 里面并没有暴露Vue 所以无法进行Vue.use的调用
2. 如果暴露出来的Vue 并且进行了Vue.use 的调用 第三方库**插槽**部分无法正常渲染。

### Vue2的配置
![image](https://user-images.githubusercontent.com/46172288/168983566-e0b7cb57-6a6c-42e0-8fa1-40ca9f94e8eb.png)

### Button.vue
![image](https://user-images.githubusercontent.com/46172288/168983765-8683b45d-e357-446a-bd76-5095ba084241.png)

### table.vue
![image](https://user-images.githubusercontent.com/46172288/168983925-36900b7a-e40d-46b3-8f05-f7edf207cec3.png)

### Vue2的渲染
![image](https://user-images.githubusercontent.com/46172288/168984245-c385c021-76fd-4695-9b26-341e3bfeaa69.png)

### Vue3的配置
![image](https://user-images.githubusercontent.com/46172288/168984519-ab94652a-633f-4cfb-a542-df64c3eaea36.png)

### App.vue
![image](https://user-images.githubusercontent.com/46172288/168984673-3f05a75f-06fc-4402-9a34-fbf7b42eb3fe.png)

### utils.js
![image](https://user-images.githubusercontent.com/46172288/168984913-dd5a9932-1748-40fb-a333-73b1e67138ad.png)

### Vue3的渲染
![image](https://user-images.githubusercontent.com/46172288/168985275-3fdadc2d-d05a-4be0-87a3-c4b13fbf7462.png)

**审查元素** 发现el-table 渲染了 但是内部**el-table-column** 没有正常渲染出来
![image](https://user-images.githubusercontent.com/46172288/168985549-cacea90a-b362-4e7f-afb9-bf4e5b299b85.png)

所以这种情况是由于`vue2ToVue3`函数导致的吗？ 如果是 应该怎么写编写才能正常加载中插槽。
如果不是 请问还有其他的方案 能够在Vue3中正常使用Vue2依赖第三方框架的组件吗？

**Comment by ckken** [comment]
2.0后已经放弃这个方案
