### ISSUE TITLE
建议增加在浏览器打开网页功能的配置

### ISSUE THREAD

**Issue by vfiee** [efoxTeam/emp#299]
每次运行emp dev命令后,还要打开控制台点击服务运行的地址,然后才能在浏览器打开
希望增加一个配置,每次运行 emp dev命令后能直接在浏览器打开

**Comment by maolovecoding** [comment]
`
module.exports = {
  server: {
    port: 9000,
    open: true // 自动打开浏览器
  },
  empShare: {}
}
`
@vfiee
