### ISSUE TITLE
expose类型生成，是否能支持.vue文件

### ISSUE THREAD

**Issue by Qeney** [efoxTeam/emp#303]
empShare: {
  name: 'microApp',
  exposes: {
    './App1': './src/App1.vue',
    './App2': './src/App2.tsx',
  },
}

上面这种配置，如果emp build后，自动生成的d.ts文件，只包含ts和tsx对应文件的导出类型，不包含.vue文件导出类型。

看了下源码实现部分，正则在匹配路径只匹配了'**/*.(ts|tsx)'，导致.vue文件无法导出类型。

具体实现可参考：https://github.com/element-plus/element-plus/blob/dev/internal/build/src/tasks/types-definitions.ts

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/blob/next/projects/vue-2-base/emp-config.js#L22

**Comment by Qeney** [comment]
![image](https://user-images.githubusercontent.com/85222064/187127678-20b70594-1728-4281-b8ae-a2dfc26058d5.png)
![image](https://user-images.githubusercontent.com/85222064/187127679-3dfa35e2-eb85-417d-9cbf-ed58dfe97a9a.png)
![image](https://user-images.githubusercontent.com/85222064/187127706-ba0ecfdd-97b5-42bf-882b-bafbccaa8b04.png)

尝试改成小写，生成的d.ts依然没有对应的类型

**Comment by Qeney** [comment]
.vue文件模块是可以正常导出的，这个没问题

但是没有生成对应的模块d.ts类型声明

**Comment by ckken** [comment]
vue ts 要观察下

**Comment by ckken** [comment]
这个应该是 vue3的项目吧
