### ISSUE TITLE
通过cdn方式引入的外部组件，在执行打包命令时 emp build 提示找不到模块

### ISSUE THREAD

**Issue by yesay** [efoxTeam/emp#306]
我把"dependencies" 下的许多外部组件使用了cdn方式引入，
但是项目打包 emp build 时，报错，找不到这些组件了。
![2022-09-01_091133](https://user-images.githubusercontent.com/3607509/187811872-07745f48-0ce5-42ff-aa9b-4770e3f78db3.png)
![2022-09-01_091847](https://user-images.githubusercontent.com/3607509/187812127-5ca7f2bb-8135-470d-a7b3-c29c1a1b2254.png)
![2022-09-01_091957](https://user-images.githubusercontent.com/3607509/187812196-d8967dd2-0ccb-4cd6-8383-96f82b56f293.png)

**Comment by ckken** [comment]
可以参考 https://github.com/efoxTeam/emp/blob/next/projects/demo/emp-config.js#L60
