### ISSUE TITLE
emp  的 demo 项目中通过cdn方式引入的组件，还需要在 dependencies 中添加依赖吗？

### ISSUE THREAD

**Issue by yesay** [efoxTeam/emp#307]
emp  的 demo 项目中通过cdn方式引入的组件，还需要在 dependencies 中添加依赖吗

cdn.js中引入组件的作用是什么？
![2022-09-01_093635](https://user-images.githubusercontent.com/3607509/187813863-a0156958-a682-4959-9fd6-293af5709f82.png)
![2022-09-01_093613](https://user-images.githubusercontent.com/3607509/187813869-263e8c64-0d0e-422a-9410-f416f033fb28.png)

**Comment by ckken** [comment]
ts 需要
