### ISSUE TITLE
建议完善发布流程，提供完整的版本changelog

### ISSUE THREAD

**Issue by typistZxd** [efoxTeam/emp#314]
- 现在changelog是跳着来的，很多小版本没有备注。
- 代码也是直接push主线，建议pr
- 上述两点导致识别不到版本之间改动了什么，也不敢升级，试过从v2.2.3 升级到 v2.4.5导致构建产物异常

**Comment by ckken** [comment]
这个是开发疏忽了 后续会增加 break change 可否看看那部分产物异常

**Comment by typistZxd** [comment]
> 

业务中部分老代码会通过import函数异步加载UMD文件

- 在v2.2.3版本中，这些UMD依赖执行完成能够正常挂载到window
- 在v2.4.5版本中，emp构建将这些UMD依赖重构打包，只保留了commonjs部分，如下

```
(function webpackUniversalModuleDefinition(root, factory) {
            if (true)
                module.exports = factory(__webpack_require__("echarts"));
            else {} // 其他AMD和root都被去除了
        }
)(window, function(__WEBPACK_EXTERNAL_MODULE_echarts__) {
```

> 从emp的changelog没能看出是哪个改动导致的问题，所以希望提供完善的信息方便开发者排查

**Comment by ckken** [comment]
是否可以提供用例测试下 最大可以点是 这里 https://github.com/efoxTeam/emp/blob/next/packages/emp/src/webpack/loader/babel-loader.ts#L73
https://github.com/efoxTeam/emp/blob/v2.2.0/packages/emp/src/webpack/loader/babel-loader.ts
