### ISSUE TITLE
shareLib共享依赖存在阻塞和未使用资源

### ISSUE THREAD

**Issue by typistZxd** [efoxTeam/emp#316]
通过sharedLib共享依赖（如组件库、echarts等），最终会将依赖通过script标签插入到页面中，即UMD形式，这样不能够很好地享受到tree-shaking，UMD全量的加载方式导致网络请求阻塞、渲染阻塞，首屏压力比较大。
对于依赖共享和首屏加载这两方面，请问有什么好的建议呢？
@ckken

**Comment by ckken** [comment]
这个是 3级共享 资源加载问题的 补救方案 esm 不会有这个问题 ，会持续关注 webpack是否有没有改进

**Comment by fantasticsoul** [comment]
可以试试工具链无关的模块联邦sdk [hel-micro](https://github.com/tnfe/hel)
