### ISSUE TITLE
能否持续更新文档呢

### ISSUE THREAD

**Issue by vellsuan** [efoxTeam/emp#318]
感觉文档不够完善，我现在遇到一个基于vue2的问题，我打包后的emp文件再另外一个项目引用，并没有拿到入口文件的几个依赖的js，还需要在项目里引用才能获取，比如jq之类的，这个是什么原因呢

**Comment by vellsuan** [comment]
而且新的配置共享第三方怎么配置呢vue的，文档上的共享方式和demo里有差异shared: ['vue/dist/vue.esm.js'], demo是对象方式引入打包文件，现在我的第三方elmentui也没能共享到，想问下现在直接用脚手架拉取的项目是否有重大问题

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/blob/main/CHANGELOG.md
