### ISSUE TITLE
库模式无法加载tsx

### ISSUE THREAD

**Issue by zjl-me** [efoxTeam/emp#325]
https://github.com/efoxTeam/emp/blob/main/packages/emp/src/webpack/wpLibMode.ts#L72

经尝试，即使通过 webpack chain 添加了新的扩展，也会被上面这段代码 所覆盖
`webpackChain: (wpChain) => {
    wpChain.resolve.extensions.add('.tsx');
  },`

**Comment by ckken** [comment]
fixed in 9e12b55c8760263b32d3b5cf9cadec2ef58eac0d
