### ISSUE TITLE
vue3 不支持setup语法糖

### ISSUE THREAD

**Issue by zhl2liuli** [efoxTeam/emp#328]
export default defineComponent({
  name: 'Layout',
  setup() {
    return () => (
      <section class={[prefixCls, `${prefixCls}__${layout.value}`, 'w-[100%] h-[100%] relative']}>
        {mobile.value && !collapse.value ? (
          <div
            class="absolute top-0 left-0 w-full h-full opacity-30 z-99 bg-[var(--el-color-black)]"
            onClick={handleClickOutside}
          ></div>
        ) : undefined}

        {renderLayout()}

        <Backtop></Backtop>

        <Setting></Setting>
      </section>
    )
  }
}) 

报错： Unexpected token, expected "," (50:15)

**Comment by ckken** [comment]
看看是否能提供完整的demo case, 官方case 可以跑 https://github.com/efoxTeam/emp/blob/main/projects/vue-3-base/src/components/TableComponent.vue#L11

**Comment by zhl2liuli** [comment]
<script lang="tsx">
import { defineComponent } from 'vue'

const dataSource = [
  {
    key: '1',
    name: '胡彦斌',
    age: 32,
    address: '西湖区湖底公园1号',
  },
  {
    key: '2',
    name: '胡彦祖',
    age: 42,
    address: '西湖区湖底公园1号',
  },
]
const columns = [
  {
    title: '姓名',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: '年龄',
    dataIndex: 'age',
    key: 'age',
  },
  {
    title: '住址',
    dataIndex: 'address',
    key: 'address',
  },
]

export default defineComponent({
  name: 'Layout',
  setup() {
    return () => (
      <ATable dataSource={dataSource} columns={columns} />
    )
  }
})
</script>


文件覆盖成这样即可

**Comment by zhl2liuli** [comment]
`
<script lang="tsx">
import { defineComponent } from 'vue'

const dataSource = [
  {
    key: '1',
    name: '胡彦斌',
    age: 32,
    address: '西湖区湖底公园1号',
  },
  {
    key: '2',
    name: '胡彦祖',
    age: 42,
    address: '西湖区湖底公园1号',
  },
]
const columns = [
  {
    title: '姓名',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: '年龄',
    dataIndex: 'age',
    key: 'age',
  },
  {
    title: '住址',
    dataIndex: 'address',
    key: 'address',
  },
]

export default defineComponent({
  name: 'Layout',
  setup() {
    return () => (
      <ATable dataSource={dataSource} columns={columns} />
    )
  }
})
</script>


`

**Comment by zhl2liuli** [comment]
![image](https://user-images.githubusercontent.com/27815046/207228788-d72e061e-8e76-4610-a06a-c66bba441d29.png)

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/blob/main/projects/vue-3-base/src/components/Count.vue

**Comment by zhl2liuli** [comment]
https://github.com/efoxTeam/emp/blob/main/projects/vue-3-base/src/components/Count.vue
这个是<script lang="ts">

还有个<script lang="tsx">
