### ISSUE TITLE
vue23还支持吗？在main branch上没看到demo

### ISSUE THREAD

**Issue by sailee-2014** [efoxTeam/emp#338]
我们有在vue3中嵌入vue2的需求，参考这篇文章，https://juejin.cn/post/6898498514813190158，发现main分支下，projects里没有vue23的目录了，找到v1分支，在v1分支上有目录，但是执行报错。
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/8059823/216505118-ec15e1c6-ac4b-4cdd-98ce-8b873e33ba55.png">
请问现在只是demo不可用了，还是vue3中使用vue2的组件功能已经废弃了？

**Comment by flyyuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sailee-2014** [comment]
自己找了下，发现是文章里的lerna不用了，使用pnpm，那没有问题了
