### ISSUE TITLE
不支持vue jsx

### ISSUE THREAD

**Issue by aov2005** [efoxTeam/emp#34]
是否需要改下babel配置？

**Comment by ckken** [comment]
有兴趣可以提个pr

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/tree/main/packages/emp-frameworks/vue3

**Comment by ckken** [comment]
fixed it:

**Comment by ckken** [comment]
fixed it 
https://github.com/efoxTeam/emp/tree/main/packages/emp-frameworks/vue3
https://github.com/efoxTeam/emp/tree/main/projects/vue3-ts
https://github.com/efoxTeam/emp/tree/main/projects/vue3-jsx
