### ISSUE TITLE
项目配置文件返回promise的时候，覆盖不了默认配置

### ISSUE THREAD

**Issue by aov2005** [efoxTeam/emp#36]
https://github.com/efoxTeam/emp/blob/be31d74e42cefd95787249826e7e653989c23aed/packages/emp-cli/helpers/project.js#L37

这行改为
```es6
await remoteConfigFn({config, env, empEnv, hot, webpack}) 
```

会不会有什么影响呢

**Comment by ckken** [comment]
加入下个版本需求

**Comment by ckken** [comment]
fixed it https://github.com/efoxTeam/emp/commit/55e273dfd741d4b1e9c6dd5dff87bd7e4f22e028
