### ISSUE TITLE
Types for repo. 

### ISSUE THREAD

**Issue by sunguru98** [efoxTeam/emp#37]
Hi, I am pretty new to this module federation and stuff, and I kinda stumbled over your repo from the GitHub issue mentioned. Is there any way that I could use the type definitions for your repository, as VSCode yells for not having types on my webpack.config.ts. I might be missing something, but help from any of the contributors would be massive. Thanks. 

(P.S I tried installing the @types thingy, yet it didn't work)

<img width="1435" alt="Screenshot 2021-01-02 at 3 18 03 PM" src="https://user-images.githubusercontent.com/32637757/103454829-b6b28b00-4d0d-11eb-955f-24f44ddbd06e.png">

**Comment by flyyuan** [comment]
fixed it https://github.com/efoxTeam/emp/commit/feb24071c8f3fbd4c640eff1b6a6ef15b0bff855
