### ISSUE TITLE
现有vue3+ts 接入，引用base的组件报错

### ISSUE THREAD

**Issue by yali213** [efoxTeam/emp#41]
![image](https://user-images.githubusercontent.com/15136519/103748410-07dcba80-503f-11eb-8747-ec378b6f1ee6.png)
![image](https://user-images.githubusercontent.com/15136519/103748440-175c0380-503f-11eb-9f57-102e0fecc201.png)
![image](https://user-images.githubusercontent.com/15136519/103748455-1e831180-503f-11eb-8794-189912b8d2a0.png)

**Comment by ckken** [comment]
fixed it https://github.com/efoxTeam/emp/blob/main/projects/vue3-ts/src/components/ButtonTsx.tsx

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/blob/1d7089acf2b05b33904fdf3d60df48077bb51ff7/packages/emp-cli/bin/emp.js#L122
