### ISSUE TITLE
emp应该如何接入sass-loader

### ISSUE THREAD

**Issue by riceapple** [efoxTeam/emp#43]

**Comment by ckken** [comment]
默认支持 https://github.com/efoxTeam/emp/blob/1d7089acf2b05b33904fdf3d60df48077bb51ff7/packages/emp-cli/webpack/config/style.js#L82

**Comment by riceapple** [comment]
> 默认支持
> 
> https://github.com/efoxTeam/emp/blob/1d7089acf2b05b33904fdf3d60df48077bb51ff7/packages/emp-cli/webpack/config/style.js#L82

/deep/关键字 编译报错，请问如何处理

**Comment by ckken** [comment]
可否把demo放到 https://codepen.io/

**Comment by riceapple** [comment]
> 可否把demo放到 https://codepen.io/

代码比较大，不太方便，帮忙看看错误信息是否有帮助，谢谢

ERROR in ./src/views/supplyChain/warehouseManagement/checkOrder/index.vue?vue&type=style&index=0&id=a3b874ae&lang=scss&scoped=true& (./node_modules/css-loader/dist/cjs.js??clonedRuleSet-4[0].rules[0].use[1]!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-4[0].rules[0].use[2]!./node_modules/@efox/emp-cli/node_modules/sass-loader/dist/cjs.js??clonedRuleSet-4[0].rules[0].use[3]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/views/supplyChain/warehouseManagement/checkOrder/index.vue?vue&type=style&index=0&id=a3b874ae&lang=scss&scoped=true&)
<e> Module build failed (from ./node_modules/@efox/emp-cli/node_modules/sass-loader/dist/cjs.js):
<e> SassError: expected selector.
<e>      ╷
<e> 1184 │ /deep/ .responsibility_radio .el-radio{
<e>      │ ^
<e>      ╵
<e>   src/views/supplyChain/warehouseManagement/checkOrder/index.vue 1184:1  root stylesheet
<e>  @ ./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js??clonedRuleSet-4[0].rules[0].use[1]!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-4[0].rules[0].use[2]!./node_modules/@efox/emp-cli/node_modules/sass-loader/dist/cjs.js??clonedRuleSet-4[0].rules[0].use[3]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/views/supplyChain/warehouseManagement/checkOrder/index.vue?vue&type=style&index=0&id=a3b874ae&lang=scss&scoped=true& 2:26-543
<e>  @ ./src/views/supplyChain/warehouseManagement/checkOrder/index.vue?vue&type=style&index=0&id=a3b874ae&lang=scss&scoped=true& 1:0-575 1:0-575
<e>  @ ./src/views/supplyChain/warehouseManagement/checkOrder/index.vue 4:0-90
<e>  @ ./src/router/supplyChain.js 35:13-37:70
<e>  @ ./src/router/index.js 21:0-40
<e>  @ ./src/bootstrap.js 3:0-30 113:10-16
<e>  @ ./src/main.js 1:0-21

**Comment by riceapple** [comment]
> 可否把demo放到 https://codepen.io/

是否sass-loader版本的问题

**Comment by riceapple** [comment]
> 可否把demo放到 https://codepen.io/
vue2项目使用官方的emp-config.js配置，css文件也没有打出来是为什么呢

**Comment by riceapple** [comment]
> 默认支持
> 
> https://github.com/efoxTeam/emp/blob/1d7089acf2b05b33904fdf3d60df48077bb51ff7/packages/emp-cli/webpack/config/style.js#L82

vue2项目使用官方的emp-config.js配置，css文件也没有打出来是为什么呢

**Comment by riceapple** [comment]
> 默认支持
> 
> https://github.com/efoxTeam/emp/blob/1d7089acf2b05b33904fdf3d60df48077bb51ff7/packages/emp-cli/webpack/config/style.js#L82

vue-loader时候没有针对单文件.vue内部的scss进行编译吧

**Comment by ckken** [comment]
你可以写个简单用例试试 不用把所有代码转了

**Comment by ckken** [comment]
回头我写个demo

**Comment by riceapple** [comment]
> 回头我写个demo

我看了一下应该是可以了 但是还想请教一个问题 我引用的element-ui组件的样式没有打到包里 是被exclude的吗

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/blob/main/projects/vue2-project/src/App.vue

**Comment by ckken** [comment]
可以放到入口试试
