### ISSUE TITLE
base 项目怎么动态加载子应用的路由?

### ISSUE THREAD

**Issue by webliving** [efoxTeam/emp#44]
例如: base-vue 项目是个基础框架页面(也有自己的路由), 那么子 project 也是个多个路由的应用. 那如何加载呢? demo 里没看出给出官方方案或有什么 API ?

**Comment by ckken** [comment]
可以参考 antd-base 和 antd-project1

**Comment by longkehuawei** [comment]
同问，有demo吗，主项目是vue ，子项目是react，发现那个路由混乱了，子项目嵌入的时候回覆盖

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/tree/main/projects/antd-project1

**Comment by ckken** [comment]
不推荐runtime 类型的框架混编

**Comment by longkehuawei** [comment]
什么意思呀？这个方案行不通吗

**Comment by longkehuawei** [comment]
我现在需求是vue 菜单里面要嵌入react的内容
