### ISSUE TITLE
请问vuex和redux的状态能否共享呢

### ISSUE THREAD

**Issue by riceapple** [efoxTeam/emp#46]

**Comment by morance** [comment]
挂window共享吧

**Comment by riceapple** [comment]
> 挂window共享吧
两个vuex能够共享吗 我也没有看到demo

**Comment by riceapple** [comment]
> 挂window共享吧

umi什么时候能与emp集成 有计划吗

**Comment by ckken** [comment]
> > 挂window共享吧
> 
> umi什么时候能与emp集成 有计划吗

这个可以放到 roadmap

**Comment by ckken** [comment]
> > 挂window共享吧
> > 两个vuex能够共享吗 我也没有看到demo

可以帮忙实战一下 具体需求 要看看怎么落地

**Comment by ckken** [comment]
暂时关闭 可以提供用例讨论
