### ISSUE TITLE
无法自定义环境变量  --env

### ISSUE THREAD

**Issue by riceapple** [efoxTeam/emp#47]

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/blob/main/projects/empty-project/.env.prod

**Comment by riceapple** [comment]
> https://github.com/efoxTeam/emp/blob/main/projects/empty-project/.env.prod

  .option('-e, --env <env>', '部署环境 dev、test、prod 默认为 prod')只有这个几个变量吗 内部没有比如test01、test02环境的逻辑分支

**Comment by ckken** [comment]
这个可以自定义 没规定用什么
