### ISSUE TITLE
vue2，babel-loader报错

### ISSUE THREAD

**Issue by alvinjstu** [efoxTeam/emp#48]
ERROR in ./src/views/login/Login.vue?vue&type=script&lang=ts& (./node_modules/babel-loader/lib/index.js??clonedRuleSet-12[0].rules[0].use[0]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/views/login/Login.vue?vue&type=script&lang=ts&)
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/alvin/Documents/testProject/src/views/login/Login.vue: Unexpected token (39:18)

  37 | })
  38 | export default class extends BaseComponent {
> 39 |   @Ref() loginForm!: Form;

package.json
 "devDependencies": {
    "@efox/emp-cli": "latest",
    "@efox/emp-vue2": "latest",
    "babel-loader": "^8.1.0",
    "vue-class-component": "^7.2.6",
    "vue-loader": "^15.9.6",
    "vue-property-decorator": "^9.1.2",
    "vuex-module-decorators": "^1.0.1"
  },

**Comment by ckken** [comment]
代码demo 共享个仓库？

**Comment by alvinjstu** [comment]
> 代码demo 共享个仓库？

https://github.com/alvinjstu/empdemo
vue2使用vue-property-decorator装饰器，实现ts,bable-loader报错

**Comment by BoatGina** [comment]
根据提供的demo，其实原则上只需要添加ts-loader，但看你是想是想vue2使用ts，所以帮你弄了一个vue2-ts模板，可以直接使用了：
npx @efox/emp-cli init   （@efox/emp-cli要> 1.6.19）

选择 vue2-ts  模板

vue2-ts  模板的具体代码：
https://github.com/efoxTeam/emp-vue2-ts-template

**Comment by BoatGina** [comment]
@alvinjstu  这个问题可以关闭了哈

**Comment by alvinjstu** [comment]
是的加了ts-loader就ok了,当然感谢你还做了template

> @alvinjstu 这个问题可以关闭了哈

是的加了ts-loader就ok了,当然感谢你还做了template
