### ISSUE TITLE
组件react多版本依赖兼容

### ISSUE THREAD

**Issue by ckken** [efoxTeam/emp#51]
适配 17~16之间的冲突

**Comment by ckken** [comment]
https://github.com/module-federation/module-federation-examples/tree/master/different-react-versions

**Comment by flyyuan** [comment]
解决方法：
https://github.com/efoxTeam/emp/wiki/%E3%80%8A%E4%B8%89%E6%AD%A5%E6%90%9E%E5%AE%9A-React-%E8%B7%A8%E7%89%88%E6%9C%AC%E8%B0%83%E7%94%A8-for-%E5%BE%AE%E5%89%8D%E7%AB%AF-EMP%E3%80%8B
