### ISSUE TITLE
React Component ErrorBoundary HOC loader

### ISSUE THREAD

**Issue by doerme** [efoxTeam/emp#54]
加载远程react组件后，react执行抛出异常时候，会导致项目白屏
https://zh-hans.reactjs.org/docs/error-boundaries.html#introducing-error-boundaries

**Comment by wengdongyang** [comment]
实际的解决的话，应该是需要配置一下共享依赖的说。

**Comment by ckken** [comment]
> 实际的解决的话，应该是需要配置一下共享依赖的说。

？

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/issues/53
