### ISSUE TITLE
无法使用antd的深色模式？

### ISSUE THREAD

**Issue by wengdongyang** [efoxTeam/emp#55]
如题。

**Comment by wengdongyang** [comment]
git@gitee.com:wengdongyang/emp-test.git

**Comment by ckken** [comment]
@dragonkuang

**Comment by dragonkuang** [comment]
能post一下代码吗？我看看

**Comment by wengdongyang** [comment]
https://github.com/wengdongyang/emp-test.git
@dragonkuang

**Comment by wengdongyang** [comment]
目前发现一种解决方式。
就是直接调用该模块的组件。
应该是webpack导致的。
@dragonkuang

**Comment by dragonkuang** [comment]
@wengdongyang 样式是有引进去的，只是被默认样式覆盖了，其实可以babel-plugin-import引入
