### ISSUE TITLE
二次封装elementui组件库创建共享组件库，使用时不生效

### ISSUE THREAD

**Issue by yeqiu741** [efoxTeam/emp#56]
通过二次封装element-ui组件库创建了一个共享的库。其他项目在使用该共享组件库中的组件的时候是未编译的状态，样式什么的都未生效，这个该怎么解决呀

**Comment by flyyuan** [comment]
相同 issue : https://github.com/efoxTeam/emp/issues/18
mf 增加 share 共享
`
...
shared: {
          vue: {eager: true, singleton: true, requiredVersion: '^3.0.2'},
        },
...
`
