### ISSUE TITLE
emp-sync-vscode-plugin   如何指定本地地址

### ISSUE THREAD

**Issue by wengdongyang** [efoxTeam/emp#59]
实际使用过程中，往往会出现其实所有项目都是由批开发者开发的。
所以本地地址如何指定

**Comment by flyyuan** [comment]
没明白你的意思。可以重新描述一下？

**Comment by wengdongyang** [comment]
是否可以支持如下写法。例如

"empSyncBase.fileURL": [{
  "url": "http://localhost:8002/index.d.ts",
  "name": "src/@deno1.d.ts"
}]

或者

"empSyncBase.fileURL": [{
  "url": "D:/www/emp/index.d.ts",
  "name": "src/@deno1.d.ts"
}]

或者

"empSyncBase.fileURL": [{
  "url": "../../otherProject/index.d.ts",
  "name": "src/@deno1.d.ts"
}]

**Comment by wengdongyang** [comment]
是否可以支持如下写法。例如

"empSyncBase.fileURL": [{
"url": "http://localhost:8002/index.d.ts",
"name": "src/@deno1.d.ts"
}]

或者

"empSyncBase.fileURL": [{
"url": "D:/www/emp/index.d.ts",
"name": "src/@deno1.d.ts"
}]

或者

"empSyncBase.fileURL": [{
"url": "../../otherProject/index.d.ts",
"name": "src/@deno1.d.ts"
}]

@flyyuan

**Comment by wengdongyang** [comment]
插件是否可以支持如下写法。例如

"empSyncBase.fileURL": [{
"url": "http://localhost:8002/index.d.ts",
"name": "src/@deno1.d.ts"
}]

或者

"empSyncBase.fileURL": [{
"url": "D:/www/emp/index.d.ts",
"name": "src/@deno1.d.ts"
}]

或者

"empSyncBase.fileURL": [{
"url": "../../otherProject/index.d.ts",
"name": "src/@deno1.d.ts"
}]

@flyyuan

**Comment by flyyuan** [comment]
localhost是支持的，但是目前还不支持本地的绝对路径和相对路径

**Comment by wengdongyang** [comment]
> 
> 
> localhost是支持的，但是目前还不支持本地的绝对路径和相对路径。
> 意思是目前只支持 http 和https 服务下的文件。
> 后续可能会进一步直接支持本地文件，通过路径使用

localhost是否有demo或者样例。实际使用中发现。好像无法生成呢。

**Comment by wengdongyang** [comment]
> 
> 
> localhost是支持的，但是目前还不支持本地的绝对路径和相对路径。
> 意思是目前只支持 http 和https 服务下的文件。
> 后续可能会进一步直接支持本地文件，通过路径使用

localhost是否可以提供样例。实际使用中发现。好像生成的文件存在一定的问题。
@flyyuan

**Comment by wengdongyang** [comment]
> 
> 
> localhost是支持的，但是目前还不支持本地的绝对路径和相对路径。
> 意思是目前只支持 http 和https 服务下的文件。
> 后续可能会进一步直接支持本地文件，通过路径使用

localhost是否可以提供样例。实际使用中发现。好像生成的文件存在一定的问题。
实际生成的文件是个空的。
@flyyuan

**Comment by wengdongyang** [comment]
是否需要一些额外的配置？

**Comment by flyyuan** [comment]
执行 `npm run emp tsc `的时候会生成类型文件
执行 `npm run emp serve ` 后启动 http 服务才能访问到文件

**Comment by wengdongyang** [comment]
thank you
