### ISSUE TITLE
Using v3 app inside of Vue2 app

### ISSUE THREAD

**Issue by ckken** [efoxTeam/emp#6]
https://github.com/module-federation/module-federation-examples/issues/504

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/issues/9

**Comment by matrunchyk** [comment]
Hi, it seems like it's a great framework you guys work on! Does it cover using Vue3 components inside of Vue2 project?

**Comment by ckken** [comment]
> Hi, it seems like it's a great framework you guys work on! Does it cover using Vue3 components inside of Vue2 project?

Yes

**Comment by matrunchyk** [comment]
Could you please show some examples how is it achieved?

**Comment by BertieGo** [comment]
> Hi, it seems like it's a great framework you guys work on! Does it cover using Vue3 components inside of Vue2 project?

Yo，bro, if you got any progress，share the demo repo with me，thx~

**Comment by flyyuan** [comment]
examples:
https://github.com/efoxTeam/emp/tree/main/projects/vue23-vue2
https://github.com/efoxTeam/emp/tree/main/projects/vue23-vue3
@matrunchyk @BertieGo
