### ISSUE TITLE
项目启动时如何区分当前是开发环境还是生产环境？如何设置代理请求？

### ISSUE THREAD

**Issue by yeqiu741** [efoxTeam/emp#61]
1、之前可以通过process.ENV.NODE_ENV来获取。
现在在emp-config.js里该值为undefined

2、设置代理请求时，在emp-config.js给config.devServer添加proxy属性值，结果没有效果，实际未进行代理转发。
     然后在node_modules里的@efox/emp-cli/webpack/config/devServer.js文件里添加同样的代码，代理转发成功。

3、还有个小疑问是在哪里进行webpack自定义一些配置，如果是emp-config.js文件里写的话好像没有效果。

**Comment by yeqiu741** [comment]
已解决

**Comment by longkehuawei** [comment]
问下这个怎么解决的呀，我也有这个问题
