### ISSUE TITLE
alias别名设置无效果

### ISSUE THREAD

**Issue by alvinjstu** [efoxTeam/emp#62]
empVue2Ts 脚手架
// 设置项目端口
  config.devServer.port(port);
// emp-config中设置别名，程序run的过程中不识别
  config.resolve.alias.set('@', resolve('src'))

错误如下：
ERROR in ./src/views/personal-center/routes.ts 5:11-74
Module not found: Error: Can't resolve '@/views/personal-center/government/Administrators.vue' in '/Users/alvin/Documents/dianzi/micro/emergency-wisdom-search/src/views/personal-center'
 @ ./src/views/ sync routes\.ts$ ./personal-center/routes.ts views/personal-center/routes.ts
 @ ./src/router/index.ts 8:20-68
 @ ./src/bootstrap.ts 6:0-30 24:10-16
 @ ./src/main.ts 3:0-21

**Comment by flyyuan** [comment]
EMP 里面获取项目路径不能直接 resolve，需要使用 resolveApp
以下是 alias @ 的例子:
`
const {resolveApp} = require('@efox/emp-cli/helpers/paths')
config.resolve.alias.set('@', `${resolveApp('.')}/src`)
`
