### ISSUE TITLE
build完成后的copyPublicFolder方法会在webpack plugin执行后才执行

### ISSUE THREAD

**Issue by aov2005** [efoxTeam/emp#66]
看到代码在该处
https://github.com/efoxTeam/emp/blob/9a5a5bc31af45ff3f8985e2054ffe500ed361e76/packages/emp-cli/scripts/build.js#L64

如果使用了类似```filemanager-webpack-plugin```的插件，打包成zip的时候，里面只包含copyPublicFolder的文件，其他静态资源没打包进去，该方法可否使用plugin实现？

**Comment by ckken** [comment]
这个要研究下 具体作用描述下？

**Comment by aov2005** [comment]
公司这边内外网隔离，又没有CI/CD，只能在发版的时候人工传打包好的zip包给运维人员进行部署，所以添加了```filemanager-webpack-plugin```插件，配置如下

```javascript
config.plugin("dist_zip").use(FileManagerPlugin, [
  {
    events: {
      onEnd: [
        {
          archive: [
            {
              source: "./dist",
              destination: `./build/${name}.${confEnv}.${version}.${buildTime}.zip`
            }
          ]
        }
      ]
    }
  }
]);
```
就是在webpack执行最后一个plugin的时候会吧./dist打包到./build/*.zip，然后昨天看到public里的静态资源文件夹没打包进去，看源码的时候才发现该情况

**Comment by aov2005** [comment]
https://github.com/efoxTeam/emp/blob/c9b56b0714ae780f5fb95374d1811f730d6fd981/packages/emp-cli/helpers/build.js#L45

好像不是插件的问题？是因为过滤了？这行代码之前是怎么考虑的呢

**Comment by aov2005** [comment]
提交了个pull request，这样应该能解决

**Comment by ckken** [comment]
我回头先review下 好像也没完全解决问题

**Comment by ckken** [comment]
filters 是为了避免重复 复制 template和 favicon 不会影响到后续操作 应该是没build 这一步构建导致的问题

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/tree/v1.7.8-copy-plugin 加了个copy 插件替换了手动复制 麻烦帮忙验证下 可以我提个版本

**Comment by aov2005** [comment]
抱歉，过年到今天才上班，我这边验证没什么问题
