### ISSUE TITLE
webpack5.20.0修复了runtimechunk: 'single'的问题。

### ISSUE THREAD

**Issue by 17biubiu** [efoxTeam/emp#69]
我的理解应该是可以用了

**Comment by 17biubiu** [comment]
![image](https://user-images.githubusercontent.com/13295895/106887252-dcbdb780-671f-11eb-8665-755ad7002658.png)

**Comment by ckken** [comment]
最新版已经更新到5.20

**Comment by 17biubiu** [comment]
> 最新版已经更新到5.20

嗯
