### ISSUE TITLE
关于加载项目中emp-config.js的问题

### ISSUE THREAD

**Issue by scottjeremy** [efoxTeam/emp#77]
在emp-cli/helpers/project.js中

`remoteConfigFn = eval(remoteConfigFn)`

为什么这段代码可以顺利执行，在执行`eval`函数中，npm包查找的目录是emp-cli中node的node_modules，并不会查找具体项目中的node_modules，所以在具体项目中引入了一些emp-cli不存在的包会报module not found

webpack配置指定了多个node_modules目录这个我知道，但与eval执行的环境无关

**Comment by ckken** [comment]
这个问题 要达到什么目的

**Comment by scottjeremy** [comment]
> 这个问题 要达到什么目的

我是想了解一下这里的npm包查找路径不应该是emp-cli中node的node_modules吗？怎么可以直接链接到项目中的node_modules呢？

**Comment by ckken** [comment]
没太明白这么问题 要解决什么问题~ 可以再discuss 里面发起讨论 暂不以issue 讨论
