### ISSUE TITLE
HMR  at Module Federation

### ISSUE THREAD

**Issue by ckken** [efoxTeam/emp#8]
https://github.com/module-federation/module-federation-examples/issues/358

**Comment by ckken** [comment]
esbuild & swc is work,babel throw error

**Comment by ckken** [comment]
https://github.com/module-federation/module-federation-examples/issues/358

**Comment by ruanyl** [comment]
The root cause of HMR not working when doing module federation is that the `remoteEntry.js` is included in the `index.html`  by default.

Check out the comment here: https://github.com/module-federation/module-federation-examples/issues/358#issuecomment-844455904
And here: https://github.com/module-federation/module-federation-examples/issues/358#issuecomment-844504427

To fix the problem, only include the chunks that you need in `HtmlWebpackPlugin`. In emp's case, it will be `chunks: ['main']`

**Comment by ckken** [comment]
> The root cause of HMR not working when doing module federation is that the `remoteEntry.js` is included in the `index.html` by default.
> 
> Check out the comment here: [module-federation/module-federation-examples#358 (comment)](https://github.com/module-federation/module-federation-examples/issues/358#issuecomment-844455904)
> And here: [module-federation/module-federation-examples#358 (comment)](https://github.com/module-federation/module-federation-examples/issues/358#issuecomment-844504427)
> 
> To fix the problem, only include the chunks that you need in `HtmlWebpackPlugin`. In emp's case, it will be `chunks: ['main']`

has demo?

**Comment by flyyuan** [comment]
remark

**Comment by ruanyl** [comment]
@ckken So just add this to HtmlWebpackPlugin `args`
```
chunks: ['index']
```

**Comment by ckken** [comment]
no work: https://github.com/efoxTeam/emp/blob/094c1136419eca75571be721bb9aba40b9d82ba9/packages/emp-cli/webpack/config/plugin.js#L71

**Comment by flyyuan** [comment]
me too. no work

**Comment by ruanyl** [comment]
Could `chunks` override somewhere? What I'm doing is just use `emp-cli` to create a react project, and I add it to `emp-config.js`. And also the name of the chunk **depends on your entry in your config**.

```
  config.plugin("html").tap((args) => {
    args[0] = {
      ...args[0],
      ...{
        title: "EMP REACT BASE",
        files: {},
        chunks: ["index"],
      },
    };
    return args;
  });

```
And it works fine for me as you can see in the screenshot, the HMR is working.

![image](https://user-images.githubusercontent.com/486382/119615023-98a60e00-be07-11eb-9923-661281a25c43.png)

**Comment by flyyuan** [comment]
your page had an update after HMR?

**Comment by ruanyl** [comment]
@flyyuan For sure, that's the whole point, isn't it?

**Comment by ckken** [comment]
hmr main problem in module federation when project expose some modules, when you haven't expose, hmr is work!

**Comment by ruanyl** [comment]
@ckken Yeah, but that's the symptom. Have you checked my comment on the other issue I linked above? https://github.com/module-federation/module-federation-examples/issues/358#issuecomment-844455904

So when you have exposed modules, ModuleFederationPlugin generates `remoteEntry.js` for you(file name is based on the config). And by default, all js assets will be injected to `index.html`, including `remoteEntry.js`.
But `remoteEntry.js` is not needed when running the current application. It's only required by the other federated applications which refer to it via `remotes`.

**Comment by ckken** [comment]
> @ckken Yeah, but that's the symptom. Have you checked my comment on the other issue I linked above? [module-federation/module-federation-examples#358 (comment)](https://github.com/module-federation/module-federation-examples/issues/358#issuecomment-844455904)
> 
> So when you have exposed modules, ModuleFederationPlugin generates `remoteEntry.js` for you(file name is based on the config). And by default, all js assets will be injected to `index.html`, including `remoteEntry.js`.
> But `remoteEntry.js` is not needed when running the current application. It's only required by the other federated applications which refer to it via `remotes`.

yes,I saw~ but the error is not caused here

**Comment by ruanyl** [comment]
@ckken Alright, so you're referring to some other issue. I see you link the issue here, I thought it might be the same issue I encountered.

**Comment by ckken** [comment]
fixed it in emp 1.8.26 may be!?

**Comment by ckken** [comment]
hot reload for react update [@efox/emp-react](https://www.npmjs.com/package/@efox/emp-react) to v1.1.6

**Comment by ckken** [comment]
fix it in  https://github.com/efoxTeam/emp/tree/v1.9.x
