### ISSUE TITLE
希望能增加自动获取声明文件的功能以方便开发

### ISSUE THREAD

**Issue by robot-liu** [efoxTeam/emp#80]
希望增加两个小功能：
1. dev时，也能生成ts声明文件
2. build或dev时，能自动从remote更新声明文件到项目中

**Comment by ckken** [comment]
dev 模式下 可以 执行 生成 https://github.com/efoxTeam/emp/blob/c7dfb94b43eae67441abcfc02c1b1d2dcfa30d90/packages/emp-cli/bin/emp.js#L110
自动同步需要安装 
https://github.com/efoxTeam/emp-sync-vscode-plugin

**Comment by robot-liu** [comment]
同步功能最好能放到emp-cli中，通过emp-config.js进行配置。这个功能似乎没有使用插件的必要。

**Comment by ckken** [comment]
目前已经支持手动同步 自动同步需要做一个服务支持 看看需不需要外置一个服务 执行 emp ts:sync

**Comment by zxgMaster** [comment]
可以在本地自己先实现一个生成+同步+dev的一个命令
"deploy": "emp tsc && node ./deploy.js && emp dev"
deploy.js:
![image](https://user-images.githubusercontent.com/32235692/109640043-ed304900-7b8a-11eb-9d44-d2158c54c80b.png)
package.json:
![image](https://user-images.githubusercontent.com/32235692/109640213-1ea91480-7b8b-11eb-9024-9bf1cf978ad4.png)
