### ISSUE TITLE
希望脚手架初始化后可以将构建文件生成到项目目录中

### ISSUE THREAD

**Issue by maki-llll** [efoxTeam/emp#81]
问题描述：因为项目需要通过配置不同指令和指令参数达到构建不同环境和不同组件分支的目的，但是构建文件在依赖包内，只能通过修改依赖包的构建文件或项目目录新建构建文件。
期望：脚手架初始化后可以将构建文件生成到项目目录里，方便修改和调整。

**Comment by ckken** [comment]
你的意思是 把webpack 配置内容都生成到项目中？

**Comment by maki-llll** [comment]
是的

**Comment by ckken** [comment]
暂不考虑支持

**Comment by ckken** [comment]
可以通过 webpack chain 修改
