### ISSUE TITLE
How to exclude files?

### ISSUE THREAD

**Issue by GruFFix** [efoxTeam/emp#84]
How can I exclude files? For example .stories for a storybook?

The directory structure is as follows:
```
Button
 Button.tsx
 Button.stories.tsx 
 index.ts
```

This code would be excluded from the d.ts.
```
declare module 'module_name/components/Button/Button.stories' {
  import { Meta } from '@storybook/react/types-6-0';
  const _default: Meta<import("@storybook/react/types-6-0").Args>;
  export default _default;
  export const Default: any;
  export const Round: any;
}
```

**Comment by antonfrolovsky** [comment]
:+1: same problem

**Comment by ckken** [comment]
@flyyuan

**Comment by flyyuan** [comment]
Can not be excluded temporarily, but does not affect the use. Code with additional type declarations is normal. Only exposes may be generated later.
