### ISSUE TITLE
emp-config.js的配置不太友好

### ISSUE THREAD

**Issue by yuki070** [efoxTeam/emp#85]
## 问题

目前`emp-config.js`的配置不太友好，需要对webpack配置有一定了解才能进行修改。既然`emp`已经将webpack的配置封装起来了，何不直接弱化webpack配置，让用户通过简单几个选项就可以完成配置？

## 建议

- 通过`export default { }`一个配置项的方式来实现，脚手架再去解析并生成最终的webpack配置？
- 整个项目都建议使用ts，这个配置文件是否也可以使用ts，可以给用户的IDE带来一些提示？

**Comment by ckken** [comment]
架构层面会生成 webpack 但是没给到 用户定制 可以通过学习 webpack chain 的方式来完成 如 vue-cli 一样

**Comment by yuki070** [comment]
> 架构层面会生成 webpack 但是没给到 用户定制 可以通过学习 webpack chain 的方式来完成 如 vue-cli 一样

我的意思是这个config文件能否像umijs那样，通过配置式来完成，而不是编码式的。

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/109906962-54a9de00-7cdc-11eb-85ab-efdb32994ab6.png)
类似这种？

**Comment by yuki070** [comment]
> ![image](https://user-images.githubusercontent.com/3890513/109906962-54a9de00-7cdc-11eb-85ab-efdb32994ab6.png)
> 类似这种？

是的。这应该比当前的编码式配置要好，降低用户的心智，只需要拿着说明书配置即可，不用做太多逻辑处理。

另外，也可以通过 emp-config.js，emp-config.local.js，emp-config.prod.js等方式，可以让用户去选择某个环境下使用那套配置。

**Comment by ckken** [comment]
emp-config 本身已经有 env 了 只需要在这个基础上做分流就可以

**Comment by ckken** [comment]
可以考虑外置多一个 webpack 的配置属性

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/discussions/88

**Comment by ckken** [comment]
1.8 已经实现 ts 配置 有 更多额外配置需求可以到 讨论区 提意见
