### ISSUE TITLE
Css module animation name property must be first or set separately

### ISSUE THREAD

**Issue by wangcylive** [efoxTeam/emp#86]
`"@efox/emp-cli": "^1.7.12"` has some problem.

`animation: 2s test-anim` build `animation: 2s :local(test-anim)`
`animation: test-anim 2s` build `animation: src-components-index-module-test-anim-2B1Nf 2s`
`animation-duration: 2s;
  animation-name: test-anim;` build `animation-duration: 2s;
    animation-name: src-components-index-module-test-anim-2B1Nf;`

**Comment by ckken** [comment]
好像是新的规范 多了个 scope 属性导致 看看文档 局部的 sass引起的问题
