### ISSUE TITLE
Module Federation in MultiFramework Environment

### ISSUE THREAD

**Issue by ckken** [efoxTeam/emp#9]
https://github.com/module-federation/module-federation-examples/issues/352
https://github.com/module-federation/module-federation-examples/issues/504

**Comment by ckken** [comment]
vue => react https://github.com/efoxTeam/emp/tree/main/projects/reactVue-react

**Comment by ckken** [comment]
RFC https://github.com/efoxTeam/rfcs/issues/3

**Comment by p0301y** [comment]
Is there a example for the same framework with different version?e.g react17.0.1 and react16.3.0

**Comment by ckken** [comment]
> Is there a example for the same framework with different version?e.g react17.0.1 and react16.3.0

It not safe

**Comment by ckken** [comment]
对跨框架诉求暂不深入研究
