### ISSUE TITLE
參數沒有被HTML tag包起來會不顯示參數

### ISSUE THREAD

**Issue by Ponpon55837** [efoxTeam/emp#94]
我在一個vue-base的專案上要exposes一個元件
```
<template>
  <div class="layout-app">
    <img src="../logo.png" width="30" />
    <h1>Demo3</h1>
    {{ msg }}
  </div>
</template>

<script>
import { ref } from "vue";
export default {
  setup() {
    const msg = ref('say my name')
  
    return { msg }
  },
};
</script>
```
可以看到上面{{ msg }} 是沒有被html標籤包起來，但是這樣在remote端接收時就會不顯示msg內容，其他部分則是正常顯示，請問有解法嗎

**Comment by ckken** [comment]
share 需要设置下

**Comment by ckken** [comment]
之前有过这个问题 @flyyuan 具体是那个？

**Comment by flyyuan** [comment]
麻烦提供一个可以复现的repo

**Comment by Ponpon55837** [comment]
https://github.com/Ponpon55837/empdebugrepo

這個repo 裡面是由vue-demo-app3發出exposes給vue23-vue3
msg寫在vue-demo-app3

感謝兩位
----------------------------
另外我有一個問題想問，請問我應該如何在現有的vue專案中直接導入emp呢
我看emp wiki上寫的都是emp init的方式

**Comment by Ponpon55837** [comment]
抱歉 我的問題有點多

今天在vue-demo-app3裡面我新增了一個click button去改變show的值，在vue-demo-app3是可以正常做動的
![image](https://user-images.githubusercontent.com/32410486/110885713-50a43e80-8322-11eb-89ba-a03e83fdf54a.png)

但是在vue23-vue3這個專案導入後，只有console.log()有做動，但是改變show的值卻沒有反應
![image](https://user-images.githubusercontent.com/32410486/110885904-a37df600-8322-11eb-87e2-86a95c345445.png)

請問這應該是哪部分出問題呢

我在確認了emp/vue23-vue2這個demo專案發現你們提供的vue2專案是可以正常跑的，但是在我自己emp init的vue3專案卻不能

程式碼我已經更新到 https://github.com/Ponpon55837/empdebugrepo 這個repo裡面了

再麻煩兩位有空的時候看看是否是我哪裡做錯了或是沒做到

**Comment by flyyuan** [comment]
![image](https://user-images.githubusercontent.com/19996552/111164648-3b0c6e80-85d9-11eb-9e91-c7e89aa16a3b.png)
需要 share vue 在 emp-config.js
