### ISSUE TITLE
使用windows构建自定义public目录报错

### ISSUE THREAD

**Issue by doerme** [efoxTeam/emp#97]
emp版本 1.7.15
自定义public目录带index.html 构建时候会报

ERROR in Conflict: Multiple assets emit different content to the same filename index.html

=== EMP Failed to compile.===

error An unexpected error occurred: "Command failed.

window系统才会  MacBook os 和 linux 不存在此问题

代码见附件

[bdgamelive_anchor.zip](https://github.com/efoxTeam/emp/files/6148717/bdgamelive_anchor.zip)

**Comment by flyyuan** [comment]
删除 node_modules 后重新 install 即可

**Comment by ckken** [comment]
https://github.com/efoxTeam/emp/commit/fbf4172638e42ba6225ae7db72f8b014ee3370f0
